package su.terrafirmagreg.core.compat.emi;

	// This file is automatically generated by the OresToFieldGuide program in Tools-Modern.
	public class ExportedOreVeinInfo {
		public static final OreVeinInfoRecipe[] RECIPES = {
			new OreVeinInfoRecipe("deep_apatite", "minecraft:overworld", 
				190, 0.3, -50, 20, 37, 0, 0, new String[] {
				"tfc:rock/raw/granite","tfc:rock/raw/diorite","tfc:rock/raw/gabbro",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("apatite", 50),new OreVeinInfoRecipe.WeightedBlock("tricalcium_phosphate", 37),new OreVeinInfoRecipe.WeightedBlock("pyrochlore", 12),},
				null),
			new OreVeinInfoRecipe("deep_asbestos", "minecraft:overworld", 
				190, 0.27, -50, 20, 35, 5, 0, new String[] {
				"tfc:rock/raw/quartzite","tfc:rock/raw/slate","tfc:rock/raw/phyllite","tfc:rock/raw/schist","tfc:rock/raw/gneiss","tfc:rock/raw/marble",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("cassiterite_sand", 55),new OreVeinInfoRecipe.WeightedBlock("asbestos", 33),new OreVeinInfoRecipe.WeightedBlock("diatomite", 11),},
				null),
			new OreVeinInfoRecipe("deep_banded_iron", "minecraft:overworld", 
				280, 0.27, -50, 20, 45, 0, 0, new String[] {
				"tfc:rock/raw/shale","tfc:rock/raw/claystone","tfc:rock/raw/limestone","tfc:rock/raw/conglomerate","tfc:rock/raw/dolomite","tfc:rock/raw/chert","tfc:rock/raw/chalk","minecraft:tuff","tfc:rock/raw/quartzite","tfc:rock/raw/slate","tfc:rock/raw/phyllite","tfc:rock/raw/schist","tfc:rock/raw/gneiss","tfc:rock/raw/marble",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("goethite", 42),new OreVeinInfoRecipe.WeightedBlock("yellow_limonite", 35),new OreVeinInfoRecipe.WeightedBlock("hematite", 21),},
				null),
			new OreVeinInfoRecipe("deep_bauxite", "minecraft:overworld", 
				420, 0.15, -50, 20, 27, 0, 0, new String[] {
				"tfc:rock/raw/granite","tfc:rock/raw/diorite","tfc:rock/raw/gabbro",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("bauxite", 30),new OreVeinInfoRecipe.WeightedBlock("ilmenite", 70),},
				null),
			new OreVeinInfoRecipe("deep_big_redstone", "minecraft:overworld", 
				270, 0.32, -50, 20, 42, 5, 0, new String[] {
				"tfc:rock/raw/granite","tfc:rock/raw/diorite","tfc:rock/raw/gabbro",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("redstone", 50),new OreVeinInfoRecipe.WeightedBlock("ruby", 30),new OreVeinInfoRecipe.WeightedBlock("cinnabar", 20),},
				null),
			new OreVeinInfoRecipe("deep_bismuth", "minecraft:overworld", 
				140, 0.27, -50, 20, 0, 60, 10, new String[] {
				"tfc:rock/raw/granite","tfc:rock/raw/diorite","tfc:rock/raw/gabbro",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("bismuth", 31),new OreVeinInfoRecipe.WeightedBlock("silver", 27),new OreVeinInfoRecipe.WeightedBlock("gold", 27),new OreVeinInfoRecipe.WeightedBlock("electrotine", 13),},
				new String[] {"ore_vein.tfg.deep_bismuth.emi.0"}),
			new OreVeinInfoRecipe("deep_copper_iron", "minecraft:overworld", 
				270, 0.25, -50, 20, 45, 0, 0, new String[] {
				"tfc:rock/raw/granite","tfc:rock/raw/diorite","tfc:rock/raw/gabbro","tfc:rock/raw/rhyolite","tfc:rock/raw/basalt","tfc:rock/raw/andesite","tfc:rock/raw/dacite",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("chalcopyrite", 37),new OreVeinInfoRecipe.WeightedBlock("goethite", 31),new OreVeinInfoRecipe.WeightedBlock("pyrite", 18),new OreVeinInfoRecipe.WeightedBlock("copper", 12),},
				null),
			new OreVeinInfoRecipe("deep_copper_sulfide", "minecraft:overworld", 
				34, 0.27, -60, -45, 27, 6, 0, new String[] {
				"tfc:rock/raw/quartzite","tfc:rock/raw/slate","tfc:rock/raw/phyllite","tfc:rock/raw/schist","tfc:rock/raw/gneiss","tfc:rock/raw/marble",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("sulfur", 80),new OreVeinInfoRecipe.WeightedBlock("bornite", 10),new OreVeinInfoRecipe.WeightedBlock("chalcocite", 10),},
				new String[] {"ore_vein.tfg.deep_copper_sulfide.emi.0"}),
			new OreVeinInfoRecipe("deep_copper_tin", "minecraft:overworld", 
				210, 0.29, -50, 20, 42, 0, 0, new String[] {
				"tfc:rock/raw/granite","tfc:rock/raw/diorite","tfc:rock/raw/gabbro","tfc:rock/raw/rhyolite","tfc:rock/raw/basalt","tfc:rock/raw/andesite","tfc:rock/raw/dacite",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("chalcopyrite", 53),new OreVeinInfoRecipe.WeightedBlock("zeolite", 23),new OreVeinInfoRecipe.WeightedBlock("cassiterite", 23),},
				null),
			new OreVeinInfoRecipe("deep_galena", "minecraft:overworld", 
				230, 0.24, -50, 20, 24, 0, 0, new String[] {
				"tfc:rock/raw/granite","tfc:rock/raw/diorite","tfc:rock/raw/gabbro",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("galena", 52),new OreVeinInfoRecipe.WeightedBlock("silver", 26),new OreVeinInfoRecipe.WeightedBlock("lead", 21),},
				new String[] {"ore_vein.tfg.deep_galena.emi.0"}),
			new OreVeinInfoRecipe("deep_graphite", "minecraft:overworld", 
				120, 0.15, -50, 0, 0, 80, 9, new String[] {
				"tfc:rock/raw/granite","tfc:rock/raw/diorite","tfc:rock/raw/gabbro",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("graphite", 60),new OreVeinInfoRecipe.WeightedBlock("diamond", 40),},
				null),
			new OreVeinInfoRecipe("deep_graphite_volcanic", "minecraft:overworld", 
				140, 0.17, -50, 0, 0, 150, 18, new String[] {
				"tfc:rock/raw/granite","tfc:rock/raw/diorite","tfc:rock/raw/gabbro",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("graphite", 60),new OreVeinInfoRecipe.WeightedBlock("diamond", 40),},
				new String[] {"ore_vein.tfg.deep_graphite_volcanic.emi.0"}),
			new OreVeinInfoRecipe("deep_iron", "minecraft:overworld", 
				160, 0.27, -50, 20, 37, 0, 0, new String[] {
				"tfc:rock/raw/shale","tfc:rock/raw/claystone","tfc:rock/raw/limestone","tfc:rock/raw/conglomerate","tfc:rock/raw/dolomite","tfc:rock/raw/chert","tfc:rock/raw/chalk","minecraft:tuff","tfc:rock/raw/quartzite","tfc:rock/raw/slate","tfc:rock/raw/phyllite","tfc:rock/raw/schist","tfc:rock/raw/gneiss","tfc:rock/raw/marble",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("goethite", 31),new OreVeinInfoRecipe.WeightedBlock("yellow_limonite", 22),new OreVeinInfoRecipe.WeightedBlock("hematite", 22),new OreVeinInfoRecipe.WeightedBlock("malachite", 22),},
				null),
			new OreVeinInfoRecipe("deep_kyanite", "minecraft:overworld", 
				160, 0.22, -50, 20, 35, 0, 0, new String[] {
				"tfc:rock/raw/quartzite","tfc:rock/raw/slate","tfc:rock/raw/phyllite","tfc:rock/raw/schist","tfc:rock/raw/gneiss","tfc:rock/raw/marble",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("kyanite", 48),new OreVeinInfoRecipe.WeightedBlock("mica", 32),new OreVeinInfoRecipe.WeightedBlock("pollucite", 20),},
				null),
			new OreVeinInfoRecipe("deep_lazurite_calcite", "minecraft:overworld", 
				130, 0.27, -50, 20, 0, 60, 10, new String[] {
				"tfc:rock/raw/quartzite","tfc:rock/raw/slate","tfc:rock/raw/phyllite","tfc:rock/raw/schist","tfc:rock/raw/gneiss","tfc:rock/raw/marble",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("lazurite", 33),new OreVeinInfoRecipe.WeightedBlock("sodalite", 26),new OreVeinInfoRecipe.WeightedBlock("lapis", 20),new OreVeinInfoRecipe.WeightedBlock("calcite", 20),},
				null),
			new OreVeinInfoRecipe("deep_magnetite", "minecraft:overworld", 
				160, 0.32, -50, 20, 41, 0, 0, new String[] {
				"tfc:rock/raw/rhyolite","tfc:rock/raw/basalt","tfc:rock/raw/andesite","tfc:rock/raw/dacite","tfc:rock/raw/quartzite","tfc:rock/raw/slate","tfc:rock/raw/phyllite","tfc:rock/raw/schist","tfc:rock/raw/gneiss","tfc:rock/raw/marble",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("magnetite", 50),new OreVeinInfoRecipe.WeightedBlock("vanadium_magnetite", 29),new OreVeinInfoRecipe.WeightedBlock("gold", 20),},
				null),
			new OreVeinInfoRecipe("deep_magnetite_olivine", "minecraft:overworld", 
				160, 0.27, -50, 20, 37, 0, 0, new String[] {
				"tfc:rock/raw/rhyolite","tfc:rock/raw/basalt","tfc:rock/raw/andesite","tfc:rock/raw/dacite","tfc:rock/raw/quartzite","tfc:rock/raw/slate","tfc:rock/raw/phyllite","tfc:rock/raw/schist","tfc:rock/raw/gneiss","tfc:rock/raw/marble",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("bentonite", 33),new OreVeinInfoRecipe.WeightedBlock("magnesite", 14),new OreVeinInfoRecipe.WeightedBlock("olivine", 7),new OreVeinInfoRecipe.WeightedBlock("glauconite_sand", 44),},
				null),
			new OreVeinInfoRecipe("deep_manganese", "minecraft:overworld", 
				240, 0.22, -50, 20, 37, 0, 0, new String[] {
				"tfc:rock/raw/granite","tfc:rock/raw/diorite","tfc:rock/raw/gabbro","tfc:rock/raw/shale","tfc:rock/raw/claystone","tfc:rock/raw/limestone","tfc:rock/raw/conglomerate","tfc:rock/raw/dolomite","tfc:rock/raw/chert","tfc:rock/raw/chalk","minecraft:tuff",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("grossular", 42),new OreVeinInfoRecipe.WeightedBlock("pyrolusite", 38),new OreVeinInfoRecipe.WeightedBlock("tantalite", 19),},
				null),
			new OreVeinInfoRecipe("deep_mineral_sand", "minecraft:overworld", 
				190, 0.27, -50, 20, 37, 0, 0, new String[] {
				"tfc:rock/raw/granite","tfc:rock/raw/diorite","tfc:rock/raw/gabbro","tfc:rock/raw/shale","tfc:rock/raw/claystone","tfc:rock/raw/limestone","tfc:rock/raw/conglomerate","tfc:rock/raw/dolomite","tfc:rock/raw/chert","tfc:rock/raw/chalk","minecraft:tuff",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("basaltic_mineral_sand", 38),new OreVeinInfoRecipe.WeightedBlock("granitic_mineral_sand", 19),new OreVeinInfoRecipe.WeightedBlock("fullers_earth", 19),new OreVeinInfoRecipe.WeightedBlock("gypsum", 23),},
				null),
			new OreVeinInfoRecipe("deep_molybdenum", "minecraft:overworld", 
				210, 0.22, -50, 20, 38, 0, 0, new String[] {
				"tfc:rock/raw/granite","tfc:rock/raw/diorite","tfc:rock/raw/gabbro",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("wulfenite", 28),new OreVeinInfoRecipe.WeightedBlock("molybdenite", 57),new OreVeinInfoRecipe.WeightedBlock("molybdenum", 7),new OreVeinInfoRecipe.WeightedBlock("powellite", 7),},
				null),
			new OreVeinInfoRecipe("deep_monazite", "minecraft:overworld", 
				290, 0.22, -50, 20, 27, 0, 0, new String[] {
				"tfc:rock/raw/quartzite","tfc:rock/raw/slate","tfc:rock/raw/phyllite","tfc:rock/raw/schist","tfc:rock/raw/gneiss","tfc:rock/raw/marble",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("bastnasite", 60),new OreVeinInfoRecipe.WeightedBlock("monazite", 30),new OreVeinInfoRecipe.WeightedBlock("neodymium", 10),},
				null),
			new OreVeinInfoRecipe("deep_nickel", "minecraft:overworld", 
				180, 0.27, -50, 20, 39, 0, 0, new String[] {
				"tfc:rock/raw/granite","tfc:rock/raw/diorite","tfc:rock/raw/gabbro",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("garnierite", 36),new OreVeinInfoRecipe.WeightedBlock("nickel", 21),new OreVeinInfoRecipe.WeightedBlock("cobaltite", 26),new OreVeinInfoRecipe.WeightedBlock("pentlandite", 15),},
				null),
			new OreVeinInfoRecipe("deep_redstone", "minecraft:overworld", 
				180, 0.27, -50, 20, 28, 0, 0, new String[] {
				"tfc:rock/raw/granite","tfc:rock/raw/diorite","tfc:rock/raw/gabbro",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("redstone", 57),new OreVeinInfoRecipe.WeightedBlock("ruby", 28),new OreVeinInfoRecipe.WeightedBlock("cinnabar", 14),},
				new String[] {"ore_vein.tfg.deep_redstone.emi.0", "ore_vein.tfg.deep_redstone.emi.1", "ore_vein.tfg.deep_redstone.emi.2"}),
			new OreVeinInfoRecipe("deep_saltpeter", "minecraft:overworld", 
				260, 0.22, -50, 20, 32, 0, 0, new String[] {
				"tfc:rock/raw/shale","tfc:rock/raw/claystone","tfc:rock/raw/limestone","tfc:rock/raw/conglomerate","tfc:rock/raw/dolomite","tfc:rock/raw/chert","tfc:rock/raw/chalk","minecraft:tuff","tfc:rock/raw/quartzite","tfc:rock/raw/slate","tfc:rock/raw/phyllite","tfc:rock/raw/schist","tfc:rock/raw/gneiss","tfc:rock/raw/marble",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("saltpeter", 48),new OreVeinInfoRecipe.WeightedBlock("diatomite", 20),new OreVeinInfoRecipe.WeightedBlock("electrotine", 16),new OreVeinInfoRecipe.WeightedBlock("alunite", 16),},
				null),
			new OreVeinInfoRecipe("deep_sapphire", "minecraft:overworld", 
				180, 0.22, -50, 20, 0, 60, 10, new String[] {
				"tfc:rock/raw/quartzite","tfc:rock/raw/slate","tfc:rock/raw/phyllite","tfc:rock/raw/schist","tfc:rock/raw/gneiss","tfc:rock/raw/marble",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("almandine", 16),new OreVeinInfoRecipe.WeightedBlock("pyrope", 24),new OreVeinInfoRecipe.WeightedBlock("sapphire", 32),new OreVeinInfoRecipe.WeightedBlock("green_sapphire", 26),},
				null),
			new OreVeinInfoRecipe("deep_scheelite", "minecraft:overworld", 
				420, 0.27, -50, 20, 25, 0, 0, new String[] {
				"tfc:rock/raw/quartzite","tfc:rock/raw/slate","tfc:rock/raw/phyllite","tfc:rock/raw/schist","tfc:rock/raw/gneiss","tfc:rock/raw/marble",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("scheelite", 42),new OreVeinInfoRecipe.WeightedBlock("tungstate", 42),new OreVeinInfoRecipe.WeightedBlock("lithium", 14),},
				null),
			new OreVeinInfoRecipe("deep_sphalerite", "minecraft:overworld", 
				180, 0.22, -50, 20, 29, 0, 0, new String[] {
				"tfc:rock/raw/quartzite","tfc:rock/raw/slate","tfc:rock/raw/phyllite","tfc:rock/raw/schist","tfc:rock/raw/gneiss","tfc:rock/raw/marble",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("sulfur", 9),new OreVeinInfoRecipe.WeightedBlock("pyrite", 27),new OreVeinInfoRecipe.WeightedBlock("sphalerite", 63),},
				new String[] {"ore_vein.tfg.deep_sphalerite.emi.0"}),
			new OreVeinInfoRecipe("deep_sulfur", "minecraft:overworld", 
				34, 0.87, -60, -45, 35, 10, 0, new String[] {
				"tfc:rock/raw/granite","tfc:rock/raw/diorite","tfc:rock/raw/gabbro","tfc:rock/raw/rhyolite","tfc:rock/raw/basalt","tfc:rock/raw/andesite","tfc:rock/raw/dacite","tfc:rock/raw/shale","tfc:rock/raw/claystone","tfc:rock/raw/limestone","tfc:rock/raw/conglomerate","tfc:rock/raw/dolomite","tfc:rock/raw/chert","tfc:rock/raw/chalk","minecraft:tuff","tfc:rock/raw/quartzite","tfc:rock/raw/slate","tfc:rock/raw/phyllite","tfc:rock/raw/schist","tfc:rock/raw/gneiss","tfc:rock/raw/marble",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("sulfur", 100),},
				new String[] {"ore_vein.tfg.deep_sulfur.emi.0"}),
			new OreVeinInfoRecipe("deep_tantalite", "minecraft:overworld", 
				290, 0.27, -50, 20, 31, 0, 0, new String[] {
				"tfc:rock/raw/quartzite","tfc:rock/raw/slate","tfc:rock/raw/phyllite","tfc:rock/raw/schist","tfc:rock/raw/gneiss","tfc:rock/raw/marble",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("grossular", 33),new OreVeinInfoRecipe.WeightedBlock("spessartine", 27),new OreVeinInfoRecipe.WeightedBlock("pyrolusite", 22),new OreVeinInfoRecipe.WeightedBlock("tantalite", 16),},
				null),
			new OreVeinInfoRecipe("deep_thorianite", "minecraft:overworld", 
				270, 0.21, -50, 20, 31, 0, 0, new String[] {
				"tfc:rock/raw/granite","tfc:rock/raw/diorite","tfc:rock/raw/gabbro",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("thorium", 44),new OreVeinInfoRecipe.WeightedBlock("uraninite", 22),new OreVeinInfoRecipe.WeightedBlock("emerald", 11),new OreVeinInfoRecipe.WeightedBlock("beryllium", 22),},
				null),
			new OreVeinInfoRecipe("deep_tin", "minecraft:overworld", 
				210, 0.27, -50, 20, 33, 0, 0, new String[] {
				"tfc:rock/raw/quartzite","tfc:rock/raw/slate","tfc:rock/raw/phyllite","tfc:rock/raw/schist","tfc:rock/raw/gneiss","tfc:rock/raw/marble",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("cassiterite", 87),new OreVeinInfoRecipe.WeightedBlock("tin", 12),},
				null),
			new OreVeinInfoRecipe("deep_topaz", "minecraft:overworld", 
				230, 0.17, -50, 20, 27, 0, 0, new String[] {
				"tfc:rock/raw/granite","tfc:rock/raw/diorite","tfc:rock/raw/gabbro",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("blue_topaz", 43),new OreVeinInfoRecipe.WeightedBlock("topaz", 31),new OreVeinInfoRecipe.WeightedBlock("chalcocite", 18),new OreVeinInfoRecipe.WeightedBlock("bornite", 6),},
				null),
			new OreVeinInfoRecipe("high_bismuth_mountain", "minecraft:overworld", 
				50, 0.25, -30, 0, 15, 0, 0, new String[] {
				"tfc:rock/raw/granite","tfc:rock/raw/diorite","tfc:rock/raw/gabbro","tfc:rock/raw/rhyolite","tfc:rock/raw/basalt","tfc:rock/raw/andesite","tfc:rock/raw/dacite","tfc:rock/raw/shale","tfc:rock/raw/claystone","tfc:rock/raw/limestone","tfc:rock/raw/conglomerate","tfc:rock/raw/dolomite","tfc:rock/raw/chert","tfc:rock/raw/chalk","minecraft:tuff","tfc:rock/raw/quartzite","tfc:rock/raw/slate","tfc:rock/raw/phyllite","tfc:rock/raw/schist","tfc:rock/raw/gneiss","tfc:rock/raw/marble",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("bismuth", 100),},
				new String[] {"ore_vein.tfg.high_bismuth_mountain.emi.0"}),
			new OreVeinInfoRecipe("high_coal", "minecraft:overworld", 
				30, 0.4, 90, 160, 30, 0, 0, new String[] {
				"tfc:rock/raw/granite","tfc:rock/raw/diorite","tfc:rock/raw/gabbro","tfc:rock/raw/rhyolite","tfc:rock/raw/basalt","tfc:rock/raw/andesite","tfc:rock/raw/dacite","tfc:rock/raw/shale","tfc:rock/raw/claystone","tfc:rock/raw/limestone","tfc:rock/raw/conglomerate","tfc:rock/raw/dolomite","tfc:rock/raw/chert","tfc:rock/raw/chalk","minecraft:tuff","tfc:rock/raw/quartzite","tfc:rock/raw/slate","tfc:rock/raw/phyllite","tfc:rock/raw/schist","tfc:rock/raw/gneiss","tfc:rock/raw/marble",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("coal", 100),},
				null),
			new OreVeinInfoRecipe("high_gypsum", "minecraft:overworld", 
				40, 0.8, 90, 140, 15, 0, 0, new String[] {
				"tfc:rock/raw/granite","tfc:rock/raw/diorite","tfc:rock/raw/gabbro","tfc:rock/raw/rhyolite","tfc:rock/raw/basalt","tfc:rock/raw/andesite","tfc:rock/raw/dacite","tfc:rock/raw/shale","tfc:rock/raw/claystone","tfc:rock/raw/limestone","tfc:rock/raw/conglomerate","tfc:rock/raw/dolomite","tfc:rock/raw/chert","tfc:rock/raw/chalk","minecraft:tuff","tfc:rock/raw/quartzite","tfc:rock/raw/slate","tfc:rock/raw/phyllite","tfc:rock/raw/schist","tfc:rock/raw/gneiss","tfc:rock/raw/marble",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("gypsum", 100),},
				null),
			new OreVeinInfoRecipe("high_lead", "minecraft:overworld", 
				60, 0.2, -30, 0, 25, 0, 0, new String[] {
				"tfc:rock/raw/granite","tfc:rock/raw/diorite","tfc:rock/raw/gabbro","tfc:rock/raw/rhyolite","tfc:rock/raw/basalt","tfc:rock/raw/andesite","tfc:rock/raw/dacite","tfc:rock/raw/shale","tfc:rock/raw/claystone","tfc:rock/raw/limestone","tfc:rock/raw/conglomerate","tfc:rock/raw/dolomite","tfc:rock/raw/chert","tfc:rock/raw/chalk","minecraft:tuff","tfc:rock/raw/quartzite","tfc:rock/raw/slate","tfc:rock/raw/phyllite","tfc:rock/raw/schist","tfc:rock/raw/gneiss","tfc:rock/raw/marble",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("lead", 60),new OreVeinInfoRecipe.WeightedBlock("silver", 40),},
				new String[] {"ore_vein.tfg.high_lead.emi.0", "ore_vein.tfg.high_lead.emi.1"}),
			new OreVeinInfoRecipe("high_realgar", "minecraft:overworld", 
				70, 0.25, -30, 1, 20, 12, 0, new String[] {
				"tfc:rock/raw/granite","tfc:rock/raw/diorite","tfc:rock/raw/gabbro","tfc:rock/raw/rhyolite","tfc:rock/raw/basalt","tfc:rock/raw/andesite","tfc:rock/raw/dacite","tfc:rock/raw/shale","tfc:rock/raw/claystone","tfc:rock/raw/limestone","tfc:rock/raw/conglomerate","tfc:rock/raw/dolomite","tfc:rock/raw/chert","tfc:rock/raw/chalk","minecraft:tuff","tfc:rock/raw/quartzite","tfc:rock/raw/slate","tfc:rock/raw/phyllite","tfc:rock/raw/schist","tfc:rock/raw/gneiss","tfc:rock/raw/marble",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("chalcopyrite", 57),new OreVeinInfoRecipe.WeightedBlock("zeolite", 28),new OreVeinInfoRecipe.WeightedBlock("realgar", 14),},
				new String[] {"ore_vein.tfg.high_realgar.emi.0"}),
			new OreVeinInfoRecipe("high_sulfur", "minecraft:overworld", 
				30, 0.9, 100, 170, 15, 0, 0, new String[] {
				"tfc:rock/raw/granite","tfc:rock/raw/diorite","tfc:rock/raw/gabbro","tfc:rock/raw/rhyolite","tfc:rock/raw/basalt","tfc:rock/raw/andesite","tfc:rock/raw/dacite","tfc:rock/raw/shale","tfc:rock/raw/claystone","tfc:rock/raw/limestone","tfc:rock/raw/conglomerate","tfc:rock/raw/dolomite","tfc:rock/raw/chert","tfc:rock/raw/chalk","minecraft:tuff","tfc:rock/raw/quartzite","tfc:rock/raw/slate","tfc:rock/raw/phyllite","tfc:rock/raw/schist","tfc:rock/raw/gneiss","tfc:rock/raw/marble",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("sulfur", 100),},
				new String[] {"ore_vein.tfg.high_sulfur.emi.0"}),
			new OreVeinInfoRecipe("high_tetrahedrite", "minecraft:overworld", 
				90, 0.25, -30, 1, 25, 0, 0, new String[] {
				"tfc:rock/raw/granite","tfc:rock/raw/diorite","tfc:rock/raw/gabbro","tfc:rock/raw/rhyolite","tfc:rock/raw/basalt","tfc:rock/raw/andesite","tfc:rock/raw/dacite","tfc:rock/raw/shale","tfc:rock/raw/claystone","tfc:rock/raw/limestone","tfc:rock/raw/conglomerate","tfc:rock/raw/dolomite","tfc:rock/raw/chert","tfc:rock/raw/chalk","minecraft:tuff","tfc:rock/raw/quartzite","tfc:rock/raw/slate","tfc:rock/raw/phyllite","tfc:rock/raw/schist","tfc:rock/raw/gneiss","tfc:rock/raw/marble",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("tetrahedrite", 50),new OreVeinInfoRecipe.WeightedBlock("copper", 30),new OreVeinInfoRecipe.WeightedBlock("stibnite", 20),},
				new String[] {"ore_vein.tfg.high_tetrahedrite.emi.0"}),
			new OreVeinInfoRecipe("high_tin", "minecraft:overworld", 
				50, 0.3, -50, 0, 35, 0, 0, new String[] {
				"tfc:rock/raw/granite","tfc:rock/raw/diorite","tfc:rock/raw/gabbro","tfc:rock/raw/rhyolite","tfc:rock/raw/basalt","tfc:rock/raw/andesite","tfc:rock/raw/dacite","tfc:rock/raw/shale","tfc:rock/raw/claystone","tfc:rock/raw/limestone","tfc:rock/raw/conglomerate","tfc:rock/raw/dolomite","tfc:rock/raw/chert","tfc:rock/raw/chalk","minecraft:tuff","tfc:rock/raw/quartzite","tfc:rock/raw/slate","tfc:rock/raw/phyllite","tfc:rock/raw/schist","tfc:rock/raw/gneiss","tfc:rock/raw/marble",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("tin", 40),new OreVeinInfoRecipe.WeightedBlock("cassiterite", 60),},
				new String[] {"ore_vein.tfg.high_tin.emi.0", "ore_vein.tfg.high_tin.emi.1"}),
			new OreVeinInfoRecipe("normal_asbestos_dry", "minecraft:overworld", 
				130, 0.28, 10, 70, 20, 10, 0, new String[] {
				"tfc:rock/raw/shale","tfc:rock/raw/claystone","tfc:rock/raw/limestone","tfc:rock/raw/conglomerate","tfc:rock/raw/dolomite","tfc:rock/raw/chert","tfc:rock/raw/chalk","minecraft:tuff","tfc:rock/raw/quartzite","tfc:rock/raw/slate","tfc:rock/raw/phyllite","tfc:rock/raw/schist","tfc:rock/raw/gneiss","tfc:rock/raw/marble",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("cassiterite_sand", 85),new OreVeinInfoRecipe.WeightedBlock("asbestos", 14),},
				new String[] {"ore_vein.tfg.normal_asbestos_dry.emi.0"}),
			new OreVeinInfoRecipe("normal_coal", "minecraft:overworld", 
				230, 0.28, 10, 70, 34, 10, 0, new String[] {
				"tfc:rock/raw/shale","tfc:rock/raw/claystone","tfc:rock/raw/limestone","tfc:rock/raw/conglomerate","tfc:rock/raw/dolomite","tfc:rock/raw/chert","tfc:rock/raw/chalk","minecraft:tuff",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("coal", 100),},
				null),
			new OreVeinInfoRecipe("normal_copper", "minecraft:overworld", 
				130, 0.33, 10, 70, 30, 10, 0, new String[] {
				"tfc:rock/raw/granite","tfc:rock/raw/diorite","tfc:rock/raw/gabbro","tfc:rock/raw/shale","tfc:rock/raw/claystone","tfc:rock/raw/limestone","tfc:rock/raw/conglomerate","tfc:rock/raw/dolomite","tfc:rock/raw/chert","tfc:rock/raw/chalk","minecraft:tuff",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("chalcopyrite", 53),new OreVeinInfoRecipe.WeightedBlock("pyrite", 30),new OreVeinInfoRecipe.WeightedBlock("copper", 15),},
				null),
			new OreVeinInfoRecipe("normal_copper_gypsum", "minecraft:overworld", 
				190, 0.28, -30, 80, 0, 35, 16, new String[] {
				"tfc:rock/raw/granite","tfc:rock/raw/diorite","tfc:rock/raw/gabbro","tfc:rock/raw/rhyolite","tfc:rock/raw/basalt","tfc:rock/raw/andesite","tfc:rock/raw/dacite","tfc:rock/raw/shale","tfc:rock/raw/claystone","tfc:rock/raw/limestone","tfc:rock/raw/conglomerate","tfc:rock/raw/dolomite","tfc:rock/raw/chert","tfc:rock/raw/chalk","minecraft:tuff","tfc:rock/raw/quartzite","tfc:rock/raw/slate","tfc:rock/raw/phyllite","tfc:rock/raw/schist","tfc:rock/raw/gneiss","tfc:rock/raw/marble",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("chalcocite", 54),new OreVeinInfoRecipe.WeightedBlock("gypsum", 13),new OreVeinInfoRecipe.WeightedBlock("cobalt", 22),new OreVeinInfoRecipe.WeightedBlock("sulfur", 9),},
				new String[] {"ore_vein.tfg.normal_copper_gypsum.emi.0"}),
			new OreVeinInfoRecipe("normal_galena", "minecraft:overworld", 
				150, 0.18, 10, 70, 23, 10, 0, new String[] {
				"tfc:rock/raw/granite","tfc:rock/raw/diorite","tfc:rock/raw/gabbro","tfc:rock/raw/rhyolite","tfc:rock/raw/basalt","tfc:rock/raw/andesite","tfc:rock/raw/dacite",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("galena", 77),new OreVeinInfoRecipe.WeightedBlock("silver", 22),},
				null),
			new OreVeinInfoRecipe("normal_garnierite", "minecraft:overworld", 
				170, 0.28, 10, 70, 25, 10, 0, new String[] {
				"tfc:rock/raw/shale","tfc:rock/raw/claystone","tfc:rock/raw/limestone","tfc:rock/raw/conglomerate","tfc:rock/raw/dolomite","tfc:rock/raw/chert","tfc:rock/raw/chalk","minecraft:tuff",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("garnierite", 52),new OreVeinInfoRecipe.WeightedBlock("nickel", 17),new OreVeinInfoRecipe.WeightedBlock("cobaltite", 30),},
				null),
			new OreVeinInfoRecipe("normal_gold", "minecraft:overworld", 
				140, 0.33, 10, 70, 24, 10, 0, new String[] {
				"tfc:rock/raw/rhyolite","tfc:rock/raw/basalt","tfc:rock/raw/andesite","tfc:rock/raw/dacite","tfc:rock/raw/quartzite","tfc:rock/raw/slate","tfc:rock/raw/phyllite","tfc:rock/raw/schist","tfc:rock/raw/gneiss","tfc:rock/raw/marble",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("gold", 57),new OreVeinInfoRecipe.WeightedBlock("magnetite", 42),},
				null),
			new OreVeinInfoRecipe("normal_iron", "minecraft:overworld", 
				130, 0.28, 10, 70, 24, 10, 0, new String[] {
				"tfc:rock/raw/rhyolite","tfc:rock/raw/basalt","tfc:rock/raw/andesite","tfc:rock/raw/dacite","tfc:rock/raw/shale","tfc:rock/raw/claystone","tfc:rock/raw/limestone","tfc:rock/raw/conglomerate","tfc:rock/raw/dolomite","tfc:rock/raw/chert","tfc:rock/raw/chalk","minecraft:tuff",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("hematite", 36),new OreVeinInfoRecipe.WeightedBlock("yellow_limonite", 63),},
				null),
			new OreVeinInfoRecipe("normal_mica", "minecraft:overworld", 
				150, 0.28, 10, 70, 21, 10, 0, new String[] {
				"tfc:rock/raw/rhyolite","tfc:rock/raw/basalt","tfc:rock/raw/andesite","tfc:rock/raw/dacite","tfc:rock/raw/quartzite","tfc:rock/raw/slate","tfc:rock/raw/phyllite","tfc:rock/raw/schist","tfc:rock/raw/gneiss","tfc:rock/raw/marble",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("mica", 58),new OreVeinInfoRecipe.WeightedBlock("kyanite", 41),},
				null),
			new OreVeinInfoRecipe("normal_quartz", "minecraft:overworld", 
				180, 0.23, 10, 70, 21, 10, 0, new String[] {
				"tfc:rock/raw/shale","tfc:rock/raw/claystone","tfc:rock/raw/limestone","tfc:rock/raw/conglomerate","tfc:rock/raw/dolomite","tfc:rock/raw/chert","tfc:rock/raw/chalk","minecraft:tuff",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("quartzite", 75),new OreVeinInfoRecipe.WeightedBlock("barite", 25),},
				null),
			new OreVeinInfoRecipe("normal_quartz_borax", "minecraft:overworld", 
				190, 0.28, -30, 70, 17, 30, 5, new String[] {
				"tfc:rock/raw/rhyolite","tfc:rock/raw/basalt","tfc:rock/raw/andesite","tfc:rock/raw/dacite",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("quartzite", 85),new OreVeinInfoRecipe.WeightedBlock("borax", 14),},
				null),
			new OreVeinInfoRecipe("normal_salt", "minecraft:overworld", 
				190, 0.26, 10, 70, 25, 10, 0, new String[] {
				"tfc:rock/raw/granite","tfc:rock/raw/diorite","tfc:rock/raw/gabbro","tfc:rock/raw/rhyolite","tfc:rock/raw/basalt","tfc:rock/raw/andesite","tfc:rock/raw/dacite","tfc:rock/raw/shale","tfc:rock/raw/claystone","tfc:rock/raw/limestone","tfc:rock/raw/conglomerate","tfc:rock/raw/dolomite","tfc:rock/raw/chert","tfc:rock/raw/chalk","minecraft:tuff","tfc:rock/raw/quartzite","tfc:rock/raw/slate","tfc:rock/raw/phyllite","tfc:rock/raw/schist","tfc:rock/raw/gneiss","tfc:rock/raw/marble",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("salt", 60),new OreVeinInfoRecipe.WeightedBlock("rock_salt", 30),new OreVeinInfoRecipe.WeightedBlock("borax", 10),},
				new String[] {"ore_vein.tfg.normal_salt.emi.0"}),
			new OreVeinInfoRecipe("normal_sphalerite", "minecraft:overworld", 
				150, 0.35, 10, 70, 18, 10, 0, new String[] {
				"tfc:rock/raw/shale","tfc:rock/raw/claystone","tfc:rock/raw/limestone","tfc:rock/raw/conglomerate","tfc:rock/raw/dolomite","tfc:rock/raw/chert","tfc:rock/raw/chalk","minecraft:tuff",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("sphalerite", 76),new OreVeinInfoRecipe.WeightedBlock("galena", 23),},
				new String[] {"ore_vein.tfg.normal_sphalerite.emi.0"}),
			new OreVeinInfoRecipe("normal_spodumene", "minecraft:overworld", 
				220, 0.23, 10, 70, 20, 8, 0, new String[] {
				"tfc:rock/raw/shale","tfc:rock/raw/claystone","tfc:rock/raw/limestone","tfc:rock/raw/conglomerate","tfc:rock/raw/dolomite","tfc:rock/raw/chert","tfc:rock/raw/chalk","minecraft:tuff","tfc:rock/raw/quartzite","tfc:rock/raw/slate","tfc:rock/raw/phyllite","tfc:rock/raw/schist","tfc:rock/raw/gneiss","tfc:rock/raw/marble",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("spodumene", 75),new OreVeinInfoRecipe.WeightedBlock("rock_salt", 25),},
				null),
			new OreVeinInfoRecipe("normal_sulfide", "minecraft:overworld", 
				150, 0.29, 10, 70, 32, 10, 0, new String[] {
				"tfc:rock/raw/granite","tfc:rock/raw/diorite","tfc:rock/raw/gabbro","tfc:rock/raw/rhyolite","tfc:rock/raw/basalt","tfc:rock/raw/andesite","tfc:rock/raw/dacite","tfc:rock/raw/shale","tfc:rock/raw/claystone","tfc:rock/raw/limestone","tfc:rock/raw/conglomerate","tfc:rock/raw/dolomite","tfc:rock/raw/chert","tfc:rock/raw/chalk","minecraft:tuff","tfc:rock/raw/quartzite","tfc:rock/raw/slate","tfc:rock/raw/phyllite","tfc:rock/raw/schist","tfc:rock/raw/gneiss","tfc:rock/raw/marble",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("sulfur", 25),new OreVeinInfoRecipe.WeightedBlock("stibnite", 18),new OreVeinInfoRecipe.WeightedBlock("bornite", 56),},
				new String[] {"ore_vein.tfg.normal_sulfide.emi.0"}),
			new OreVeinInfoRecipe("normal_tarkianite", "minecraft:overworld", 
				170, 0.28, 10, 70, 0, 60, 10, new String[] {
				"tfc:rock/raw/rhyolite","tfc:rock/raw/basalt","tfc:rock/raw/andesite","tfc:rock/raw/dacite","tfc:rock/raw/quartzite","tfc:rock/raw/slate","tfc:rock/raw/phyllite","tfc:rock/raw/schist","tfc:rock/raw/gneiss","tfc:rock/raw/marble",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("tarkianite", 53),new OreVeinInfoRecipe.WeightedBlock("borax", 30),new OreVeinInfoRecipe.WeightedBlock("trona", 15),},
				new String[] {"ore_vein.tfg.normal_tarkianite.emi.0", "ore_vein.tfg.normal_tarkianite.emi.1", "ore_vein.tfg.normal_tarkianite.emi.2", "ore_vein.tfg.normal_tarkianite.emi.3"}),
			new OreVeinInfoRecipe("sand_mineral_sand", "minecraft:overworld", 
				190, 0.24, -5, 1, 34, 0, 0, new String[] {
				"tfc:sand/black","tfc:sand/brown","tfc:sand/green","tfc:sand/pink","tfc:sand/red","tfc:sand/white","tfc:sand/yellow",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("basaltic_mineral_sand", 38),new OreVeinInfoRecipe.WeightedBlock("granitic_mineral_sand", 19),new OreVeinInfoRecipe.WeightedBlock("fullers_earth", 19),new OreVeinInfoRecipe.WeightedBlock("glauconite_sand", 23),},
				new String[] {"ore_vein.tfg.sand_mineral_sand.emi.0", "ore_vein.tfg.sand_mineral_sand.emi.1"}),
			new OreVeinInfoRecipe("sand_tin", "minecraft:overworld", 
				190, 0.2, -5, 1, 35, 0, 0, new String[] {
				"tfc:sand/black","tfc:sand/brown","tfc:sand/green","tfc:sand/pink","tfc:sand/red","tfc:sand/white","tfc:sand/yellow",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("cassiterite_sand", 100),},
				new String[] {"ore_vein.tfg.sand_tin.emi.0", "ore_vein.tfg.sand_tin.emi.1"}),
			new OreVeinInfoRecipe("surface_bismuth", "minecraft:overworld", 
				70, 0.25, -30, -10, 15, 0, 0, new String[] {
				"tfc:rock/raw/rhyolite","tfc:rock/raw/basalt","tfc:rock/raw/andesite","tfc:rock/raw/dacite","tfc:rock/raw/shale","tfc:rock/raw/claystone","tfc:rock/raw/limestone","tfc:rock/raw/conglomerate","tfc:rock/raw/dolomite","tfc:rock/raw/chert","tfc:rock/raw/chalk","minecraft:tuff",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("bismuth", 100),},
				new String[] {"ore_vein.tfg.surface_bismuth.emi.0", "ore_vein.tfg.surface_bismuth.emi.1", "ore_vein.tfg.surface_bismuth.emi.2", "ore_vein.tfg.surface_bismuth.emi.3"}),
			new OreVeinInfoRecipe("surface_coal", "minecraft:overworld", 
				90, 0.45, -20, 1, 15, 0, 0, new String[] {
				"tfc:rock/raw/rhyolite","tfc:rock/raw/basalt","tfc:rock/raw/andesite","tfc:rock/raw/dacite",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("coal", 100),},
				new String[] {"ore_vein.tfg.surface_coal.emi.0", "ore_vein.tfg.surface_coal.emi.1", "ore_vein.tfg.surface_coal.emi.2"}),
			new OreVeinInfoRecipe("surface_cobaltite", "minecraft:overworld", 
				120, 0.1, -20, -5, 15, 0, 0, new String[] {
				"tfc:rock/raw/rhyolite","tfc:rock/raw/basalt","tfc:rock/raw/andesite","tfc:rock/raw/dacite","tfc:rock/raw/quartzite","tfc:rock/raw/slate","tfc:rock/raw/phyllite","tfc:rock/raw/schist","tfc:rock/raw/gneiss","tfc:rock/raw/marble",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("cobaltite", 100),},
				new String[] {"ore_vein.tfg.surface_cobaltite.emi.0", "ore_vein.tfg.surface_cobaltite.emi.1", "ore_vein.tfg.surface_cobaltite.emi.2"}),
			new OreVeinInfoRecipe("surface_gold", "minecraft:overworld", 
				85, 0.25, -20, -5, 15, 0, 0, new String[] {
				"tfc:rock/raw/rhyolite","tfc:rock/raw/basalt","tfc:rock/raw/andesite","tfc:rock/raw/dacite",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("gold", 100),},
				new String[] {"ore_vein.tfg.surface_gold.emi.0", "ore_vein.tfg.surface_gold.emi.1", "ore_vein.tfg.surface_gold.emi.2"}),
			new OreVeinInfoRecipe("surface_hematite", "minecraft:overworld", 
				75, 0.3, -20, -5, 15, 0, 0, new String[] {
				"tfc:rock/raw/rhyolite","tfc:rock/raw/basalt","tfc:rock/raw/andesite","tfc:rock/raw/dacite",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("hematite", 100),},
				new String[] {"ore_vein.tfg.surface_hematite.emi.0", "ore_vein.tfg.surface_hematite.emi.1", "ore_vein.tfg.surface_hematite.emi.2"}),
			new OreVeinInfoRecipe("surface_limonite", "minecraft:overworld", 
				120, 0.25, -20, -5, 15, 0, 0, new String[] {
				"tfc:rock/raw/shale","tfc:rock/raw/claystone","tfc:rock/raw/limestone","tfc:rock/raw/conglomerate","tfc:rock/raw/dolomite","tfc:rock/raw/chert","tfc:rock/raw/chalk","minecraft:tuff",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("yellow_limonite", 100),},
				new String[] {"ore_vein.tfg.surface_limonite.emi.0", "ore_vein.tfg.surface_limonite.emi.1", "ore_vein.tfg.surface_limonite.emi.2"}),
			new OreVeinInfoRecipe("surface_magnetite", "minecraft:overworld", 
				120, 0.25, -20, -5, 15, 0, 0, new String[] {
				"tfc:rock/raw/shale","tfc:rock/raw/claystone","tfc:rock/raw/limestone","tfc:rock/raw/conglomerate","tfc:rock/raw/dolomite","tfc:rock/raw/chert","tfc:rock/raw/chalk","minecraft:tuff",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("magnetite", 100),},
				new String[] {"ore_vein.tfg.surface_magnetite.emi.0", "ore_vein.tfg.surface_magnetite.emi.1", "ore_vein.tfg.surface_magnetite.emi.2"}),
			new OreVeinInfoRecipe("surface_malachite", "minecraft:overworld", 
				70, 0.2, -20, -5, 15, 0, 0, new String[] {
				"tfc:rock/raw/shale","tfc:rock/raw/claystone","tfc:rock/raw/limestone","tfc:rock/raw/conglomerate","tfc:rock/raw/dolomite","tfc:rock/raw/chert","tfc:rock/raw/chalk","minecraft:tuff","tfc:rock/raw/quartzite","tfc:rock/raw/slate","tfc:rock/raw/phyllite","tfc:rock/raw/schist","tfc:rock/raw/gneiss","tfc:rock/raw/marble",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("malachite", 100),},
				new String[] {"ore_vein.tfg.surface_malachite.emi.0", "ore_vein.tfg.surface_malachite.emi.1", "ore_vein.tfg.surface_malachite.emi.2"}),
			new OreVeinInfoRecipe("surface_mica", "minecraft:overworld", 
				120, 0.1, -20, -5, 10, 0, 0, new String[] {
				"tfc:rock/raw/granite","tfc:rock/raw/diorite","tfc:rock/raw/gabbro","tfc:rock/raw/rhyolite","tfc:rock/raw/basalt","tfc:rock/raw/andesite","tfc:rock/raw/dacite",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("mica", 100),},
				new String[] {"ore_vein.tfg.surface_mica.emi.0", "ore_vein.tfg.surface_mica.emi.1", "ore_vein.tfg.surface_mica.emi.2"}),
			new OreVeinInfoRecipe("surface_native_copper", "minecraft:overworld", 
				70, 0.2, -20, -5, 15, 0, 0, new String[] {
				"tfc:rock/raw/rhyolite","tfc:rock/raw/basalt","tfc:rock/raw/andesite","tfc:rock/raw/dacite",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("copper", 100),},
				new String[] {"ore_vein.tfg.surface_native_copper.emi.0", "ore_vein.tfg.surface_native_copper.emi.1", "ore_vein.tfg.surface_native_copper.emi.2"}),
			new OreVeinInfoRecipe("surface_nickel", "minecraft:overworld", 
				90, 0.15, -20, -5, 15, 0, 0, new String[] {
				"tfc:rock/raw/shale","tfc:rock/raw/claystone","tfc:rock/raw/limestone","tfc:rock/raw/conglomerate","tfc:rock/raw/dolomite","tfc:rock/raw/chert","tfc:rock/raw/chalk","minecraft:tuff",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("garnierite", 100),},
				new String[] {"ore_vein.tfg.surface_nickel.emi.0", "ore_vein.tfg.surface_nickel.emi.1", "ore_vein.tfg.surface_nickel.emi.2"}),
			new OreVeinInfoRecipe("surface_salpeter", "minecraft:overworld", 
				80, 0.3, -20, -5, 20, 0, 0, new String[] {
				"tfc:rock/raw/rhyolite","tfc:rock/raw/basalt","tfc:rock/raw/andesite","tfc:rock/raw/dacite",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("saltpeter", 100),},
				new String[] {"ore_vein.tfg.surface_salpeter.emi.0", "ore_vein.tfg.surface_salpeter.emi.1", "ore_vein.tfg.surface_salpeter.emi.2"}),
			new OreVeinInfoRecipe("surface_sphalerite", "minecraft:overworld", 
				80, 0.25, -20, -5, 15, 0, 0, new String[] {
				"tfc:rock/raw/granite","tfc:rock/raw/diorite","tfc:rock/raw/gabbro","tfc:rock/raw/rhyolite","tfc:rock/raw/basalt","tfc:rock/raw/andesite","tfc:rock/raw/dacite",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("sphalerite", 100),},
				new String[] {"ore_vein.tfg.surface_sphalerite.emi.0", "ore_vein.tfg.surface_sphalerite.emi.1", "ore_vein.tfg.surface_sphalerite.emi.2"}),
			new OreVeinInfoRecipe("surface_sylvite_salt", "minecraft:overworld", 
				80, 0.15, -20, -5, 15, 0, 0, new String[] {
				"tfc:rock/raw/shale","tfc:rock/raw/claystone","tfc:rock/raw/limestone","tfc:rock/raw/conglomerate","tfc:rock/raw/dolomite","tfc:rock/raw/chert","tfc:rock/raw/chalk","minecraft:tuff","tfc:rock/raw/quartzite","tfc:rock/raw/slate","tfc:rock/raw/phyllite","tfc:rock/raw/schist","tfc:rock/raw/gneiss","tfc:rock/raw/marble",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("salt", 60),new OreVeinInfoRecipe.WeightedBlock("rock_salt", 40),},
				new String[] {"ore_vein.tfg.surface_sylvite_salt.emi.0", "ore_vein.tfg.surface_sylvite_salt.emi.1", "ore_vein.tfg.surface_sylvite_salt.emi.2"}),
			new OreVeinInfoRecipe("surface_tetrahedrite", "minecraft:overworld", 
				70, 0.2, -20, -5, 15, 0, 0, new String[] {
				"tfc:rock/raw/granite","tfc:rock/raw/diorite","tfc:rock/raw/gabbro","tfc:rock/raw/quartzite","tfc:rock/raw/slate","tfc:rock/raw/phyllite","tfc:rock/raw/schist","tfc:rock/raw/gneiss","tfc:rock/raw/marble",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("tetrahedrite", 100),},
				new String[] {"ore_vein.tfg.surface_tetrahedrite.emi.0", "ore_vein.tfg.surface_tetrahedrite.emi.1", "ore_vein.tfg.surface_tetrahedrite.emi.2"}),
			new OreVeinInfoRecipe("surface_tricalcium_phosphate", "minecraft:overworld", 
				90, 0.3, -20, -5, 15, 0, 0, new String[] {
				"tfc:rock/raw/shale","tfc:rock/raw/claystone","tfc:rock/raw/limestone","tfc:rock/raw/conglomerate","tfc:rock/raw/dolomite","tfc:rock/raw/chert","tfc:rock/raw/chalk","minecraft:tuff",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("tricalcium_phosphate", 100),},
				new String[] {"ore_vein.tfg.surface_tricalcium_phosphate.emi.0", "ore_vein.tfg.surface_tricalcium_phosphate.emi.1", "ore_vein.tfg.surface_tricalcium_phosphate.emi.2"}),
			new OreVeinInfoRecipe("deep_mars_chromite", "ad_astra:mars", 
				370, 0.3, -30, 0, 60, 0, 0, new String[] {
				"gtceu:red_granite","tfc:rock/raw/gabbro","tfc:rock/raw/diorite","tfc:rock/raw/granite",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("redstone", 45),new OreVeinInfoRecipe.WeightedBlock("ruby", 35),new OreVeinInfoRecipe.WeightedBlock("chromite", 20),},
				null),
			new OreVeinInfoRecipe("deep_mars_pitchblende", "ad_astra:mars", 
				370, 0.3, -30, 0, 60, 0, 0, new String[] {
				"gtceu:red_granite","tfc:rock/raw/gabbro","tfc:rock/raw/diorite","tfc:rock/raw/granite",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("pitchblende", 52),new OreVeinInfoRecipe.WeightedBlock("thorium", 26),new OreVeinInfoRecipe.WeightedBlock("uraninite", 21),},
				null),
			new OreVeinInfoRecipe("deep_mars_sheldonite", "ad_astra:mars", 
				370, 0.3, -30, 0, 60, 0, 0, new String[] {
				"gtceu:red_granite","tfc:rock/raw/gabbro","tfc:rock/raw/diorite","tfc:rock/raw/granite",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("bornite", 35),new OreVeinInfoRecipe.WeightedBlock("cooperite", 25),new OreVeinInfoRecipe.WeightedBlock("nickel", 25),new OreVeinInfoRecipe.WeightedBlock("platinum", 15),},
				null),
			new OreVeinInfoRecipe("mars_almandine", "ad_astra:mars", 
				280, 0.35, 0, 70, 65, 8, 0, new String[] {
				"ad_astra:mars_stone","ad_astra:venus_stone","gtceu:red_granite","tfc:rock/raw/diorite","tfc:rock/raw/gabbro","tfc:rock/raw/shale","tfc:rock/raw/claystone","tfc:rock/raw/limestone","tfc:rock/raw/dolomite","tfc:rock/raw/chert",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("almandine", 36),new OreVeinInfoRecipe.WeightedBlock("pyrope", 26),new OreVeinInfoRecipe.WeightedBlock("sapphire", 15),new OreVeinInfoRecipe.WeightedBlock("green_sapphire", 15),new OreVeinInfoRecipe.WeightedBlock("hematite", 5),},
				null),
			new OreVeinInfoRecipe("mars_apatite", "ad_astra:mars", 
				220, 0.25, 0, 70, 45, 0, 0, new String[] {
				"ad_astra:venus_stone","gtceu:red_granite","tfc:rock/raw/shale","tfc:rock/raw/claystone","tfc:rock/raw/limestone","tfc:rock/raw/conglomerate","tfc:rock/raw/chert","tfc:rock/raw/chalk","tfc:rock/raw/basalt","tfc:rock/raw/dacite",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("apatite", 47),new OreVeinInfoRecipe.WeightedBlock("tricalcium_phosphate", 33),new OreVeinInfoRecipe.WeightedBlock("pyrochlore", 14),new OreVeinInfoRecipe.WeightedBlock("hematite", 4),},
				null),
			new OreVeinInfoRecipe("mars_beryllium", "ad_astra:mars", 
				350, 0.35, -20, 50, 0, 40, 8, new String[] {
				"tfc:rock/raw/rhyolite","tfc:rock/raw/basalt","tfc:rock/raw/andesite","tfc:rock/raw/dacite",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("beryllium", 35),new OreVeinInfoRecipe.WeightedBlock("emerald", 50),new OreVeinInfoRecipe.WeightedBlock("realgar", 15),},
				null),
			new OreVeinInfoRecipe("mars_coal", "ad_astra:mars", 
				215, 0.6, 0, 70, 55, 0, 0, new String[] {
				"ad_astra:mars_stone","ad_astra:venus_stone","gtceu:red_granite","tfc:rock/raw/granite","tfc:rock/raw/diorite","tfc:rock/raw/claystone","tfc:rock/raw/conglomerate","tfc:rock/raw/dolomite","tfc:rock/raw/chalk","tfc:rock/raw/basalt","tfc:rock/raw/dacite",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("coal", 70),new OreVeinInfoRecipe.WeightedBlock("hematite", 30),},
				null),
			new OreVeinInfoRecipe("mars_copper", "ad_astra:mars", 
				220, 0.4, 0, 70, 50, 0, 0, new String[] {
				"ad_astra:mars_stone","ad_astra:venus_stone","tfc:rock/raw/shale","tfc:rock/raw/claystone","tfc:rock/raw/limestone","tfc:rock/raw/conglomerate","tfc:rock/raw/dolomite","tfc:rock/raw/basalt","tfc:rock/raw/dacite","tfc:rock/raw/quartzite",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("chalcopyrite", 65),new OreVeinInfoRecipe.WeightedBlock("copper", 20),new OreVeinInfoRecipe.WeightedBlock("pyrite", 10),new OreVeinInfoRecipe.WeightedBlock("hematite", 5),},
				null),
			new OreVeinInfoRecipe("mars_galena", "ad_astra:mars", 
				215, 0.4, 0, 70, 50, 0, 0, new String[] {
				"ad_astra:mars_stone","gtceu:red_granite","tfc:rock/raw/granite","tfc:rock/raw/gabbro","tfc:rock/raw/shale","tfc:rock/raw/claystone","tfc:rock/raw/chert","tfc:rock/raw/chalk","tfc:rock/raw/basalt","tfc:rock/raw/dacite",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("galena", 40),new OreVeinInfoRecipe.WeightedBlock("silver", 20),new OreVeinInfoRecipe.WeightedBlock("lead", 33),new OreVeinInfoRecipe.WeightedBlock("hematite", 6),},
				null),
			new OreVeinInfoRecipe("mars_gold", "ad_astra:mars", 
				230, 0.4, 0, 70, 40, 0, 0, new String[] {
				"tfc:rock/raw/granite","tfc:rock/raw/diorite","tfc:rock/raw/gabbro","tfc:rock/raw/shale","tfc:rock/raw/claystone","tfc:rock/raw/chert","tfc:rock/raw/chalk",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("green_sapphire", 5),new OreVeinInfoRecipe.WeightedBlock("bauxite", 20),new OreVeinInfoRecipe.WeightedBlock("electrotine", 20),new OreVeinInfoRecipe.WeightedBlock("gold", 55),},
				null),
			new OreVeinInfoRecipe("mars_graphite", "ad_astra:mars", 
				220, 0.4, 0, 120, 0, 60, 9, new String[] {
				"tfc:rock/raw/gabbro","tfc:rock/raw/diorite","tfc:rock/raw/granite","gtceu:red_granite","ad_astra:mars_stone","tfc:rock/raw/dacite","ad_astra:venus_stone",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("graphite", 45),new OreVeinInfoRecipe.WeightedBlock("coal", 25),new OreVeinInfoRecipe.WeightedBlock("diamond", 20),new OreVeinInfoRecipe.WeightedBlock("hematite", 10),},
				null),
			new OreVeinInfoRecipe("mars_hematite", "ad_astra:mars", 
				210, 0.4, 0, 70, 40, 0, 0, new String[] {
				"ad_astra:mars_stone","gtceu:red_granite","tfc:rock/raw/claystone","tfc:rock/raw/limestone","tfc:rock/raw/conglomerate","tfc:rock/raw/dolomite","tfc:rock/raw/basalt","tfc:rock/raw/dacite","tfc:rock/raw/quartzite",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("hematite", 50),new OreVeinInfoRecipe.WeightedBlock("yellow_limonite", 30),new OreVeinInfoRecipe.WeightedBlock("goethite", 15),new OreVeinInfoRecipe.WeightedBlock("gold", 5),},
				null),
			new OreVeinInfoRecipe("mars_lapis", "ad_astra:mars", 
				200, 0.25, 0, 70, 30, 0, 0, new String[] {
				"ad_astra:mars_stone","tfc:rock/raw/shale","tfc:rock/raw/limestone","tfc:rock/raw/dolomite","tfc:rock/raw/chert","tfc:rock/raw/chalk",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("lazurite", 35),new OreVeinInfoRecipe.WeightedBlock("sodalite", 25),new OreVeinInfoRecipe.WeightedBlock("lapis", 25),new OreVeinInfoRecipe.WeightedBlock("calcite", 15),},
				null),
			new OreVeinInfoRecipe("mars_lubricant", "ad_astra:mars", 
				220, 0.25, 0, 70, 40, 0, 0, new String[] {
				"ad_astra:mars_stone","gtceu:red_granite","tfc:rock/raw/granite","tfc:rock/raw/diorite","tfc:rock/raw/shale","tfc:rock/raw/claystone","tfc:rock/raw/limestone","tfc:rock/raw/conglomerate","tfc:rock/raw/dolomite","tfc:rock/raw/dacite","tfc:rock/raw/quartzite",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("soapstone", 21),new OreVeinInfoRecipe.WeightedBlock("talc", 21),new OreVeinInfoRecipe.WeightedBlock("glauconite_sand", 7),new OreVeinInfoRecipe.WeightedBlock("trona", 35),new OreVeinInfoRecipe.WeightedBlock("pentlandite", 7),new OreVeinInfoRecipe.WeightedBlock("hematite", 7),},
				null),
			new OreVeinInfoRecipe("mars_neodynium", "ad_astra:mars", 
				215, 0.4, 0, 70, 45, 0, 0, new String[] {
				"ad_astra:mars_stone","ad_astra:venus_stone","tfc:rock/raw/diorite","tfc:rock/raw/gabbro","tfc:rock/raw/dolomite","tfc:rock/raw/chert","tfc:rock/raw/chalk","tfc:rock/raw/basalt","tfc:rock/raw/quartzite",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("bastnasite", 58),new OreVeinInfoRecipe.WeightedBlock("monazite", 29),new OreVeinInfoRecipe.WeightedBlock("neodymium", 5),new OreVeinInfoRecipe.WeightedBlock("hematite", 5),},
				null),
			new OreVeinInfoRecipe("mars_nickel", "ad_astra:mars", 
				250, 0.4, 0, 70, 55, 0, 0, new String[] {
				"ad_astra:mars_stone","gtceu:red_granite","tfc:rock/raw/granite","tfc:rock/raw/shale","tfc:rock/raw/claystone","tfc:rock/raw/limestone","tfc:rock/raw/chalk","tfc:rock/raw/basalt","tfc:rock/raw/dacite","tfc:rock/raw/quartzite",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("garnierite", 35),new OreVeinInfoRecipe.WeightedBlock("nickel", 28),new OreVeinInfoRecipe.WeightedBlock("cobaltite", 28),new OreVeinInfoRecipe.WeightedBlock("hematite", 7),},
				null),
			new OreVeinInfoRecipe("mars_pitchblende", "ad_astra:mars", 
				220, 0.55, 0, 70, 20, 0, 0, new String[] {
				"ad_astra:mars_stone","ad_astra:venus_stone","gtceu:red_granite","tfc:rock/raw/diorite","tfc:rock/raw/gabbro","tfc:rock/raw/shale","tfc:rock/raw/conglomerate","tfc:rock/raw/dolomite","tfc:rock/raw/dacite","tfc:rock/raw/quartzite",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("pitchblende", 41),new OreVeinInfoRecipe.WeightedBlock("thorium", 29),new OreVeinInfoRecipe.WeightedBlock("hematite", 29),},
				null),
			new OreVeinInfoRecipe("mars_quartzite", "ad_astra:mars", 
				210, 0.3, 0, 70, 40, 0, 0, new String[] {
				"ad_astra:mars_stone","ad_astra:venus_stone","gtceu:red_granite","tfc:rock/raw/granite","tfc:rock/raw/shale","tfc:rock/raw/claystone","tfc:rock/raw/limestone","tfc:rock/raw/chert","tfc:rock/raw/chalk","tfc:rock/raw/quartzite",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("quartzite", 41),new OreVeinInfoRecipe.WeightedBlock("barite", 35),new OreVeinInfoRecipe.WeightedBlock("asbestos", 17),new OreVeinInfoRecipe.WeightedBlock("hematite", 5),},
				null),
			new OreVeinInfoRecipe("mars_salt", "ad_astra:mars", 
				210, 0.4, 0, 70, 40, 6, 0, new String[] {
				"ad_astra:mars_stone","ad_astra:venus_stone","gtceu:red_granite","tfc:rock/raw/granite","tfc:rock/raw/diorite","tfc:rock/raw/claystone","tfc:rock/raw/limestone","tfc:rock/raw/chert","tfc:rock/raw/chalk","tfc:rock/raw/quartzite",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("rock_salt", 20),new OreVeinInfoRecipe.WeightedBlock("salt", 30),new OreVeinInfoRecipe.WeightedBlock("lepidolite", 15),new OreVeinInfoRecipe.WeightedBlock("spodumene", 35),},
				null),
			new OreVeinInfoRecipe("mars_stibnite", "ad_astra:mars", 
				210, 0.4, 0, 70, 40, 0, 0, new String[] {
				"ad_astra:mars_stone","ad_astra:venus_stone","gtceu:red_granite","tfc:rock/raw/diorite","tfc:rock/raw/gabbro","tfc:rock/raw/shale","tfc:rock/raw/dolomite","tfc:rock/raw/chert","tfc:rock/raw/chalk","tfc:rock/raw/basalt","tfc:rock/raw/dacite","tfc:rock/raw/quartzite",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("tetrahedrite", 47),new OreVeinInfoRecipe.WeightedBlock("copper", 28),new OreVeinInfoRecipe.WeightedBlock("stibnite", 19),new OreVeinInfoRecipe.WeightedBlock("hematite", 4),},
				null),
			new OreVeinInfoRecipe("mars_sulfur", "ad_astra:mars", 
				215, 0.2, 0, 70, 45, 0, 0, new String[] {
				"ad_astra:mars_stone","ad_astra:venus_stone","tfc:rock/raw/granite","tfc:rock/raw/diorite","tfc:rock/raw/gabbro","tfc:rock/raw/chert","tfc:rock/raw/chalk","tfc:rock/raw/basalt","tfc:rock/raw/dacite",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("sulfur", 14),new OreVeinInfoRecipe.WeightedBlock("pyrite", 42),new OreVeinInfoRecipe.WeightedBlock("sphalerite", 23),new OreVeinInfoRecipe.WeightedBlock("hematite", 19),},
				null),
			new OreVeinInfoRecipe("mars_tantalite", "ad_astra:mars", 
				230, 0.3, 0, 70, 42, 0, 0, new String[] {
				"ad_astra:mars_stone","ad_astra:venus_stone","gtceu:red_granite","tfc:rock/raw/gabbro","tfc:rock/raw/shale","tfc:rock/raw/claystone","tfc:rock/raw/limestone","tfc:rock/raw/chert","tfc:rock/raw/chalk","tfc:rock/raw/basalt",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("grossular", 10),new OreVeinInfoRecipe.WeightedBlock("spessartine", 10),new OreVeinInfoRecipe.WeightedBlock("pyrolusite", 42),new OreVeinInfoRecipe.WeightedBlock("tantalite", 36),},
				null),
			new OreVeinInfoRecipe("mars_tungsten", "ad_astra:mars", 
				280, 0.45, 0, 70, 50, 0, 0, new String[] {
				"gtceu:red_granite","tfc:rock/raw/shale","tfc:rock/raw/claystone","tfc:rock/raw/limestone","tfc:rock/raw/dolomite","tfc:rock/raw/chert","tfc:rock/raw/chalk","tfc:rock/raw/basalt",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("scheelite", 42),new OreVeinInfoRecipe.WeightedBlock("tungstate", 33),new OreVeinInfoRecipe.WeightedBlock("lithium", 19),new OreVeinInfoRecipe.WeightedBlock("hematite", 4),},
				null),
			new OreVeinInfoRecipe("mars_surface_bismuthinite", "ad_astra:mars", 
				140, 0.25, 80, 180, 45, 0, 0, new String[] {
				"ad_astra:mars_stone","ad_astra:venus_stone","gtceu:red_granite","tfc:rock/raw/granite","tfc:rock/raw/diorite","tfc:rock/raw/gabbro","tfc:rock/raw/shale","tfc:rock/raw/claystone","tfc:rock/raw/limestone","tfc:rock/raw/conglomerate","tfc:rock/raw/dolomite","tfc:rock/raw/chert","tfc:rock/raw/chalk","tfc:rock/raw/basalt","tfc:rock/raw/dacite","tfc:rock/raw/quartzite",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("bismuth", 40),new OreVeinInfoRecipe.WeightedBlock("hematite", 20),new OreVeinInfoRecipe.WeightedBlock("sulfur", 20),new OreVeinInfoRecipe.WeightedBlock("gypsum", 20),},
				null),
			new OreVeinInfoRecipe("mars_surface_cassiterite", "ad_astra:mars", 
				135, 0.25, 80, 180, 45, 0, 0, new String[] {
				"ad_astra:mars_stone","ad_astra:venus_stone","gtceu:red_granite","tfc:rock/raw/granite","tfc:rock/raw/diorite","tfc:rock/raw/gabbro","tfc:rock/raw/shale","tfc:rock/raw/claystone","tfc:rock/raw/limestone","tfc:rock/raw/conglomerate","tfc:rock/raw/dolomite","tfc:rock/raw/chert","tfc:rock/raw/chalk","tfc:rock/raw/basalt","tfc:rock/raw/dacite","tfc:rock/raw/quartzite",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("cassiterite", 55),new OreVeinInfoRecipe.WeightedBlock("tin", 35),new OreVeinInfoRecipe.WeightedBlock("saltpeter", 10),},
				null),
			new OreVeinInfoRecipe("mars_surface_hematite", "ad_astra:mars", 
				140, 0.25, 80, 180, 45, 0, 0, new String[] {
				"ad_astra:mars_stone","ad_astra:venus_stone","gtceu:red_granite","tfc:rock/raw/granite","tfc:rock/raw/diorite","tfc:rock/raw/gabbro","tfc:rock/raw/shale","tfc:rock/raw/claystone","tfc:rock/raw/limestone","tfc:rock/raw/conglomerate","tfc:rock/raw/dolomite","tfc:rock/raw/chert","tfc:rock/raw/chalk","tfc:rock/raw/basalt","tfc:rock/raw/dacite","tfc:rock/raw/quartzite",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("hematite", 55),new OreVeinInfoRecipe.WeightedBlock("yellow_limonite", 33),new OreVeinInfoRecipe.WeightedBlock("gold", 5),new OreVeinInfoRecipe.WeightedBlock("calcite", 5),},
				null),
			new OreVeinInfoRecipe("mars_surface_nickel_galena", "ad_astra:mars", 
				150, 0.25, 80, 180, 45, 0, 0, new String[] {
				"ad_astra:mars_stone","ad_astra:venus_stone","gtceu:red_granite","tfc:rock/raw/granite","tfc:rock/raw/diorite","tfc:rock/raw/gabbro","tfc:rock/raw/shale","tfc:rock/raw/claystone","tfc:rock/raw/limestone","tfc:rock/raw/conglomerate","tfc:rock/raw/dolomite","tfc:rock/raw/chert","tfc:rock/raw/chalk","tfc:rock/raw/basalt","tfc:rock/raw/dacite","tfc:rock/raw/quartzite",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("sphalerite", 17),new OreVeinInfoRecipe.WeightedBlock("nickel", 23),new OreVeinInfoRecipe.WeightedBlock("galena", 35),new OreVeinInfoRecipe.WeightedBlock("silver", 11),new OreVeinInfoRecipe.WeightedBlock("cobaltite", 11),},
				null),
			new OreVeinInfoRecipe("mars_surface_tetrahedrite", "ad_astra:mars", 
				140, 0.25, 80, 180, 45, 0, 0, new String[] {
				"ad_astra:mars_stone","ad_astra:venus_stone","gtceu:red_granite","tfc:rock/raw/granite","tfc:rock/raw/diorite","tfc:rock/raw/gabbro","tfc:rock/raw/shale","tfc:rock/raw/claystone","tfc:rock/raw/limestone","tfc:rock/raw/conglomerate","tfc:rock/raw/dolomite","tfc:rock/raw/chert","tfc:rock/raw/chalk","tfc:rock/raw/basalt","tfc:rock/raw/dacite","tfc:rock/raw/quartzite",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("tetrahedrite", 57),new OreVeinInfoRecipe.WeightedBlock("copper", 19),new OreVeinInfoRecipe.WeightedBlock("stibnite", 19),new OreVeinInfoRecipe.WeightedBlock("redstone", 4),},
				null),
			new OreVeinInfoRecipe("moon_apatite", "ad_astra:moon", 
				250, 0.3, 0, 100, 35, 0, 0, new String[] {
				"tfc:rock/raw/diorite","ad_astra:moon_stone","ad_astra:moon_deepslate",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("apatite", 23),new OreVeinInfoRecipe.WeightedBlock("tricalcium_phosphate", 33),new OreVeinInfoRecipe.WeightedBlock("pyrochlore", 38),new OreVeinInfoRecipe.WeightedBlock("olivine", 4),},
				null),
			new OreVeinInfoRecipe("moon_bauxite", "ad_astra:moon", 
				200, 0.35, 0, 80, 40, 0, 0, new String[] {
				"tfc:rock/raw/basalt","ad_astra:moon_stone","ad_astra:moon_deepslate","ad_astra:glacio_stone","tfc:rock/raw/diorite","tfc:rock/raw/rhyolite",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("bauxite", 36),new OreVeinInfoRecipe.WeightedBlock("ilmenite", 42),new OreVeinInfoRecipe.WeightedBlock("armalcolite", 21),},
				null),
			new OreVeinInfoRecipe("moon_beryllium", "ad_astra:moon", 
				260, 0.35, 0, 120, 0, 70, 8, new String[] {
				"tfc:rock/raw/basalt","ad_astra:moon_stone","ad_astra:glacio_stone",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("beryllium", 31),new OreVeinInfoRecipe.WeightedBlock("emerald", 45),new OreVeinInfoRecipe.WeightedBlock("thorium", 0),new OreVeinInfoRecipe.WeightedBlock("olivine", 4),new OreVeinInfoRecipe.WeightedBlock("rock_salt", 18),},
				null),
			new OreVeinInfoRecipe("moon_cassiterite", "ad_astra:moon", 
				210, 0.3, 10, 128, 35, 0, 0, new String[] {
				"tfc:rock/raw/granite","tfc:rock/raw/diorite","tfc:rock/raw/gabbro","ad_astra:moon_deepslate",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("chalcopyrite", 35),new OreVeinInfoRecipe.WeightedBlock("zeolite", 5),new OreVeinInfoRecipe.WeightedBlock("cassiterite", 41),new OreVeinInfoRecipe.WeightedBlock("tin", 17),},
				null),
			new OreVeinInfoRecipe("moon_sheldonite", "ad_astra:moon", 
				260, 0.3, 0, 70, 30, 0, 0, new String[] {
				"tfc:rock/raw/basalt","tfc:rock/raw/andesite","ad_astra:glacio_stone",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("bornite", 35),new OreVeinInfoRecipe.WeightedBlock("cooperite", 25),new OreVeinInfoRecipe.WeightedBlock("platinum", 15),new OreVeinInfoRecipe.WeightedBlock("nickel", 25),},
				null),
			new OreVeinInfoRecipe("moon_desh", "ad_astra:moon", 
				230, 0.35, 10, 80, 30, 0, 0, new String[] {
				"tfc:rock/raw/andesite","tfc:rock/raw/dacite","tfc:rock/raw/gabbro","tfc:rock/raw/basalt",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("desh", 25),new OreVeinInfoRecipe.WeightedBlock("ilmenite", 30),new OreVeinInfoRecipe.WeightedBlock("aluminium", 25),new OreVeinInfoRecipe.WeightedBlock("armalcolite", 20),},
				null),
			new OreVeinInfoRecipe("moon_garnet", "ad_astra:moon", 
				230, 0.35, 10, 128, 35, 7, 0, new String[] {
				"tfc:rock/raw/rhyolite","tfc:rock/raw/basalt","tfc:rock/raw/andesite",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("red_garnet", 9),new OreVeinInfoRecipe.WeightedBlock("yellow_garnet", 14),new OreVeinInfoRecipe.WeightedBlock("amethyst", 38),new OreVeinInfoRecipe.WeightedBlock("opal", 38),},
				null),
			new OreVeinInfoRecipe("moon_garnierite", "ad_astra:moon", 
				250, 0.35, 5, 85, 45, 0, 0, new String[] {
				"tfc:rock/raw/gabbro","tfc:rock/raw/diorite","tfc:rock/raw/rhyolite",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("garnierite", 23),new OreVeinInfoRecipe.WeightedBlock("nickel", 19),new OreVeinInfoRecipe.WeightedBlock("cobaltite", 19),new OreVeinInfoRecipe.WeightedBlock("pentlandite", 23),new OreVeinInfoRecipe.WeightedBlock("cobalt", 14),},
				null),
			new OreVeinInfoRecipe("moon_gold", "ad_astra:moon", 
				170, 0.35, 10, 80, 35, 10, 0, new String[] {
				"tfc:rock/raw/basalt","tfc:rock/raw/granite","tfc:rock/raw/diorite",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("green_sapphire", 5),new OreVeinInfoRecipe.WeightedBlock("bauxite", 20),new OreVeinInfoRecipe.WeightedBlock("magnetite", 20),new OreVeinInfoRecipe.WeightedBlock("gold", 55),},
				null),
			new OreVeinInfoRecipe("moon_graphite", "ad_astra:moon", 
				260, 0.4, 0, 120, 0, 60, 9, new String[] {
				"tfc:rock/raw/basalt","ad_astra:moon_stone","ad_astra:glacio_stone","tfc:rock/raw/gabbro","tfc:rock/raw/basalt",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("graphite", 52),new OreVeinInfoRecipe.WeightedBlock("diamond", 36),new OreVeinInfoRecipe.WeightedBlock("olivine", 10),},
				null),
			new OreVeinInfoRecipe("moon_gypsum", "ad_astra:moon", 
				180, 0.3, 10, 100, 30, 9, 0, new String[] {
				"ad_astra:moon_stone","ad_astra:glacio_stone","ad_astra:moon_deepslate",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("borax", 20),new OreVeinInfoRecipe.WeightedBlock("calcite", 25),new OreVeinInfoRecipe.WeightedBlock("alunite", 15),new OreVeinInfoRecipe.WeightedBlock("gypsum", 35),new OreVeinInfoRecipe.WeightedBlock("olivine", 5),},
				null),
			new OreVeinInfoRecipe("moon_lubricant", "ad_astra:moon", 
				190, 0.25, 0, 66, 30, 0, 0, new String[] {
				"tfc:rock/raw/diorite","tfc:rock/raw/gabbro","ad_astra:moon_stone","ad_astra:moon_deepslate","tfc:rock/raw/basalt",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("soapstone", 30),new OreVeinInfoRecipe.WeightedBlock("talc", 20),new OreVeinInfoRecipe.WeightedBlock("glauconite_sand", 25),new OreVeinInfoRecipe.WeightedBlock("pentlandite", 15),new OreVeinInfoRecipe.WeightedBlock("trona", 10),},
				null),
			new OreVeinInfoRecipe("moon_magnetite", "ad_astra:moon", 
				280, 0.25, 0, 90, 50, 0, 0, new String[] {
				"tfc:rock/raw/diorite","tfc:rock/raw/gabbro","ad_astra:moon_stone","ad_astra:moon_deepslate",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("magnetite", 25),new OreVeinInfoRecipe.WeightedBlock("vanadium_magnetite", 15),new OreVeinInfoRecipe.WeightedBlock("chromite", 40),new OreVeinInfoRecipe.WeightedBlock("gold", 15),new OreVeinInfoRecipe.WeightedBlock("sapphire", 5),},
				null),
			new OreVeinInfoRecipe("moon_manganese", "ad_astra:moon", 
				215, 0.35, 5, 80, 30, 0, 0, new String[] {
				"tfc:rock/raw/andesite","tfc:rock/raw/basalt","tfc:rock/raw/gabbro","tfc:rock/raw/dacite","tfc:rock/raw/basalt","ad_astra:moon_deepslate",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("grossular", 37),new OreVeinInfoRecipe.WeightedBlock("spessartine", 25),new OreVeinInfoRecipe.WeightedBlock("pyrolusite", 25),new OreVeinInfoRecipe.WeightedBlock("tantalite", 12),},
				null),
			new OreVeinInfoRecipe("moon_mica", "ad_astra:moon", 
				250, 0.25, 0, 120, 35, 0, 0, new String[] {
				"tfc:rock/raw/diorite","tfc:rock/raw/gabbro","ad_astra:moon_stone","ad_astra:moon_deepslate",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("kyanite", 33),new OreVeinInfoRecipe.WeightedBlock("mica", 23),new OreVeinInfoRecipe.WeightedBlock("bauxite", 23),new OreVeinInfoRecipe.WeightedBlock("aluminium", 14),new OreVeinInfoRecipe.WeightedBlock("olivine", 4),},
				null),
			new OreVeinInfoRecipe("moon_molybdenum", "ad_astra:moon", 
				245, 0.35, 0, 50, 35, 0, 0, new String[] {
				"tfc:rock/raw/basalt","tfc:rock/raw/dacite","tfc:rock/raw/gabbro","ad_astra:moon_deepslate",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("wulfenite", 44),new OreVeinInfoRecipe.WeightedBlock("molybdenite", 33),new OreVeinInfoRecipe.WeightedBlock("powellite", 16),new OreVeinInfoRecipe.WeightedBlock("olivine", 5),},
				null),
			new OreVeinInfoRecipe("moon_monazite", "ad_astra:moon", 
				310, 0.2, 0, 70, 40, 0, 0, new String[] {
				"ad_astra:glacio_stone","tfc:rock/raw/andesite","tfc:rock/raw/dacite","tfc:rock/raw/rhyolite",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("bastnasite", 61),new OreVeinInfoRecipe.WeightedBlock("monazite", 30),new OreVeinInfoRecipe.WeightedBlock("neodymium", 6),new OreVeinInfoRecipe.WeightedBlock("olivine", 1),},
				null),
			new OreVeinInfoRecipe("moon_pyrolusite", "ad_astra:moon", 
				210, 0.25, 20, 80, 35, 0, 0, new String[] {
				"tfc:rock/raw/andesite","tfc:rock/raw/basalt","tfc:rock/raw/gabbro","ad_astra:moon_stone","ad_astra:moon_deepslate",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("pyrolusite", 38),new OreVeinInfoRecipe.WeightedBlock("cobaltite", 23),new OreVeinInfoRecipe.WeightedBlock("cobalt", 23),new OreVeinInfoRecipe.WeightedBlock("tantalite", 14),},
				null),
			new OreVeinInfoRecipe("moon_quartz", "ad_astra:moon", 
				230, 0.3, 10, 100, 45, 0, 0, new String[] {
				"tfc:rock/raw/basalt","ad_astra:moon_deepslate","tfc:rock/raw/gabbro","ad_astra:moon_stone","tfc:rock/raw/diorite","ad_astra:glacio_stone","tfc:rock/raw/dacite","tfc:rock/raw/rhyolite","tfc:rock/raw/andesite",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("quartzite", 20),new OreVeinInfoRecipe.WeightedBlock("certus_quartz", 45),new OreVeinInfoRecipe.WeightedBlock("nether_quartz", 30),new OreVeinInfoRecipe.WeightedBlock("barite", 5),},
				null),
			new OreVeinInfoRecipe("moon_redstone", "ad_astra:moon", 
				250, 0.2, 20, 100, 35, 0, 0, new String[] {
				"tfc:rock/raw/dacite","ad_astra:glacio_stone","tfc:rock/raw/andesite",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("redstone", 42),new OreVeinInfoRecipe.WeightedBlock("ruby", 33),new OreVeinInfoRecipe.WeightedBlock("cinnabar", 19),new OreVeinInfoRecipe.WeightedBlock("olivine", 4),},
				null),
			new OreVeinInfoRecipe("moon_saltpeter", "ad_astra:moon", 
				210, 0.3, 0, 90, 30, 0, 0, new String[] {
				"tfc:rock/raw/rhyolite","tfc:rock/raw/andesite","ad_astra:moon_deepslate","tfc:rock/raw/dacite",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("saltpeter", 29),new OreVeinInfoRecipe.WeightedBlock("soapstone", 20),new OreVeinInfoRecipe.WeightedBlock("electrotine", 37),new OreVeinInfoRecipe.WeightedBlock("talc", 12),},
				null),
			new OreVeinInfoRecipe("moon_sapphire", "ad_astra:moon", 
				280, 0.35, 0, 100, 28, 8, 0, new String[] {
				"tfc:rock/raw/basalt","ad_astra:moon_deepslate",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("almandine", 38),new OreVeinInfoRecipe.WeightedBlock("pyrope", 27),new OreVeinInfoRecipe.WeightedBlock("sapphire", 16),new OreVeinInfoRecipe.WeightedBlock("green_sapphire", 16),new OreVeinInfoRecipe.WeightedBlock("olivine", 2),},
				null),
			new OreVeinInfoRecipe("moon_scheelite", "ad_astra:moon", 
				200, 0.4, 0, 70, 20, 0, 0, new String[] {
				"tfc:rock/raw/rhyolite","ad_astra:glacio_stone","tfc:rock/raw/gabbro",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("scheelite", 40),new OreVeinInfoRecipe.WeightedBlock("tungstate", 50),new OreVeinInfoRecipe.WeightedBlock("lithium", 10),},
				null),
			new OreVeinInfoRecipe("moon_silver", "ad_astra:moon", 
				210, 0.35, 20, 75, 30, 0, 0, new String[] {
				"ad_astra:moon_stone","ad_astra:moon_deepslate","tfc:rock/raw/rhyolite","tfc:rock/raw/diorite","tfc:rock/raw/dacite",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("galena", 28),new OreVeinInfoRecipe.WeightedBlock("silver", 42),new OreVeinInfoRecipe.WeightedBlock("lead", 23),new OreVeinInfoRecipe.WeightedBlock("olivine", 4),},
				null),
			new OreVeinInfoRecipe("moon_sphalerite", "ad_astra:moon", 
				205, 0.35, 2, 75, 35, 0, 0, new String[] {
				"tfc:rock/raw/basalt","tfc:rock/raw/andesite","tfc:rock/raw/gabbro","tfc:rock/raw/dacite","ad_astra:glacio_stone",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("desh", 10),new OreVeinInfoRecipe.WeightedBlock("sphalerite", 50),new OreVeinInfoRecipe.WeightedBlock("pyrite", 40),},
				null),
			new OreVeinInfoRecipe("moon_tetrahedrite", "ad_astra:moon", 
				190, 0.3, 50, 128, 35, 0, 0, new String[] {
				"tfc:rock/raw/dacite","ad_astra:glacio_stone","tfc:rock/raw/andesite","tfc:rock/raw/rhyolite",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("tetrahedrite", 40),new OreVeinInfoRecipe.WeightedBlock("copper", 15),new OreVeinInfoRecipe.WeightedBlock("stibnite", 20),new OreVeinInfoRecipe.WeightedBlock("chalcocite", 25),},
				null),
			new OreVeinInfoRecipe("moon_topaz", "ad_astra:moon", 
				210, 0.35, 0, 120, 45, 16, 0, new String[] {
				"tfc:rock/raw/basalt","ad_astra:moon_deepslate","tfc:rock/raw/gabbro","ad_astra:moon_stone","tfc:rock/raw/diorite","ad_astra:glacio_stone","tfc:rock/raw/dacite","tfc:rock/raw/rhyolite","tfc:rock/raw/andesite",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("blue_topaz", 35),new OreVeinInfoRecipe.WeightedBlock("topaz", 25),new OreVeinInfoRecipe.WeightedBlock("chalcocite", 25),new OreVeinInfoRecipe.WeightedBlock("bornite", 15),},
				null),
			new OreVeinInfoRecipe("nether_anthracite", "minecraft:the_nether", 
				35, 0.8, 48, 127, 13, 4, 0, new String[] {
				"minecraft:deepslate",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("anthracite", 100),},
				null),
			new OreVeinInfoRecipe("nether_apatite", "minecraft:the_nether", 
				220, 0.35, 48, 128, 39, 0, 0, new String[] {
				"tfc:rock/raw/schist","tfc:rock/raw/gneiss",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("apatite", 50),new OreVeinInfoRecipe.WeightedBlock("tricalcium_phosphate", 35),new OreVeinInfoRecipe.WeightedBlock("pyrochlore", 15),},
				null),
			new OreVeinInfoRecipe("nether_basaltic_sands", "minecraft:the_nether", 
				160, 0.4, 48, 128, 48, 9, 0, new String[] {
				"tfc:rock/raw/granite","tfc:rock/raw/basalt",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("basaltic_mineral_sand", 35),new OreVeinInfoRecipe.WeightedBlock("granitic_mineral_sand", 25),new OreVeinInfoRecipe.WeightedBlock("fullers_earth", 25),new OreVeinInfoRecipe.WeightedBlock("gypsum", 15),},
				null),
			new OreVeinInfoRecipe("nether_beryllium", "minecraft:the_nether", 
				300, 0.45, 32, 128, 0, 60, 12, new String[] {
				"minecraft:deepslate","minecraft:blackstone","tfc:rock/raw/basalt","minecraft:dripstone_block",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("beryllium", 33),new OreVeinInfoRecipe.WeightedBlock("emerald", 47),new OreVeinInfoRecipe.WeightedBlock("thorium", 0),new OreVeinInfoRecipe.WeightedBlock("rock_salt", 18),},
				null),
			new OreVeinInfoRecipe("nether_cassiterite", "minecraft:the_nether", 
				170, 0.5, 32, 128, 45, 0, 0, new String[] {
				"tfc:rock/raw/granite","tfc:rock/raw/diorite","tfc:rock/raw/gabbro","tfc:rock/raw/gneiss","tfc:rock/raw/schist","minecraft:blackstone",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("cassiterite", 36),new OreVeinInfoRecipe.WeightedBlock("tin", 54),new OreVeinInfoRecipe.WeightedBlock("saltpeter", 9),},
				null),
			new OreVeinInfoRecipe("nether_sheldonite", "minecraft:the_nether", 
				250, 0.4, 0, 128, 35, 0, 0, new String[] {
				"minecraft:deepslate","minecraft:blackstone","tfc:rock/raw/basalt","minecraft:dripstone_block",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("bornite", 41),new OreVeinInfoRecipe.WeightedBlock("cooperite", 29),new OreVeinInfoRecipe.WeightedBlock("platinum", 5),new OreVeinInfoRecipe.WeightedBlock("nickel", 23),},
				null),
			new OreVeinInfoRecipe("nether_copper", "minecraft:the_nether", 
				170, 0.5, 32, 128, 45, 0, 0, new String[] {
				"minecraft:deepslate","minecraft:blackstone","tfc:rock/raw/basalt","minecraft:dripstone_block",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("chalcopyrite", 20),new OreVeinInfoRecipe.WeightedBlock("hematite", 5),new OreVeinInfoRecipe.WeightedBlock("pyrite", 10),new OreVeinInfoRecipe.WeightedBlock("copper", 65),},
				null),
			new OreVeinInfoRecipe("nether_garnet", "minecraft:the_nether", 
				230, 0.35, 0, 128, 45, 8, 0, new String[] {
				"minecraft:deepslate","minecraft:blackstone","tfc:rock/raw/basalt","minecraft:dripstone_block",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("red_garnet", 9),new OreVeinInfoRecipe.WeightedBlock("yellow_garnet", 14),new OreVeinInfoRecipe.WeightedBlock("amethyst", 38),new OreVeinInfoRecipe.WeightedBlock("opal", 38),},
				null),
			new OreVeinInfoRecipe("nether_garnet_tin", "minecraft:the_nether", 
				270, 0.35, 24, 128, 45, 0, 0, new String[] {
				"minecraft:deepslate","minecraft:blackstone","minecraft:dripstone_block","tfc:rock/raw/granite","tfc:rock/raw/diorite","tfc:rock/raw/gabbro","tfc:rock/raw/schist","tfc:rock/raw/gneiss",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("cassiterite_sand", 35),new OreVeinInfoRecipe.WeightedBlock("garnet_sand", 25),new OreVeinInfoRecipe.WeightedBlock("asbestos", 25),new OreVeinInfoRecipe.WeightedBlock("diatomite", 15),},
				null),
			new OreVeinInfoRecipe("nether_garnierite", "minecraft:the_nether", 
				160, 0.5, 16, 128, 45, 0, 0, new String[] {
				"tfc:rock/raw/gabbro","tfc:rock/raw/diorite","minecraft:blackstone",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("garnierite", 23),new OreVeinInfoRecipe.WeightedBlock("nickel", 19),new OreVeinInfoRecipe.WeightedBlock("cobaltite", 19),new OreVeinInfoRecipe.WeightedBlock("pentlandite", 23),new OreVeinInfoRecipe.WeightedBlock("cobalt", 14),},
				null),
			new OreVeinInfoRecipe("nether_goethite", "minecraft:the_nether", 
				240, 0.45, 0, 128, 37, 0, 0, new String[] {
				"minecraft:deepslate","minecraft:blackstone","tfc:rock/raw/basalt","minecraft:dripstone_block",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("goethite", 50),new OreVeinInfoRecipe.WeightedBlock("yellow_limonite", 15),new OreVeinInfoRecipe.WeightedBlock("hematite", 15),new OreVeinInfoRecipe.WeightedBlock("malachite", 20),},
				null),
			new OreVeinInfoRecipe("nether_gold", "minecraft:the_nether", 
				260, 0.55, 0, 128, 37, 0, 0, new String[] {
				"tfc:rock/raw/gabbro","tfc:rock/raw/diorite","tfc:rock/raw/gneiss","tfc:rock/raw/granite","tfc:rock/raw/schist","minecraft:blackstone",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("goethite", 5),new OreVeinInfoRecipe.WeightedBlock("yellow_limonite", 5),new OreVeinInfoRecipe.WeightedBlock("hematite", 15),new OreVeinInfoRecipe.WeightedBlock("gold", 75),},
				null),
			new OreVeinInfoRecipe("nether_graphite", "minecraft:the_nether", 
				120, 0.35, 0, 128, 0, 60, 12, new String[] {
				"tfc:rock/raw/gabbro","tfc:rock/raw/gneiss","tfc:rock/raw/diorite","tfc:rock/raw/schist","tfc:rock/raw/granite","minecraft:blackstone",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("graphite", 45),new OreVeinInfoRecipe.WeightedBlock("diamond", 40),new OreVeinInfoRecipe.WeightedBlock("coal", 15),},
				null),
			new OreVeinInfoRecipe("nether_gypsum", "minecraft:the_nether", 
				180, 0.4, 32, 128, 40, 9, 0, new String[] {
				"minecraft:deepslate","minecraft:dripstone_block","minecraft:blackstone",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("borax", 20),new OreVeinInfoRecipe.WeightedBlock("calcite", 30),new OreVeinInfoRecipe.WeightedBlock("fullers_earth", 15),new OreVeinInfoRecipe.WeightedBlock("gypsum", 35),},
				null),
			new OreVeinInfoRecipe("nether_hematite", "minecraft:the_nether", 
				220, 0.45, 0, 128, 35, 0, 0, new String[] {
				"minecraft:deepslate","minecraft:blackstone","tfc:rock/raw/basalt","minecraft:dripstone_block",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("goethite", 25),new OreVeinInfoRecipe.WeightedBlock("yellow_limonite", 15),new OreVeinInfoRecipe.WeightedBlock("hematite", 35),new OreVeinInfoRecipe.WeightedBlock("gold", 5),new OreVeinInfoRecipe.WeightedBlock("ruby", 20),},
				null),
			new OreVeinInfoRecipe("nether_lapis", "minecraft:the_nether", 
				220, 0.35, 32, 128, 40, 0, 0, new String[] {
				"minecraft:deepslate","minecraft:dripstone_block","minecraft:blackstone",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("lazurite", 35),new OreVeinInfoRecipe.WeightedBlock("sodalite", 25),new OreVeinInfoRecipe.WeightedBlock("lapis", 25),new OreVeinInfoRecipe.WeightedBlock("calcite", 15),},
				null),
			new OreVeinInfoRecipe("nether_lubricant", "minecraft:the_nether", 
				250, 0.35, 32, 128, 41, 0, 0, new String[] {
				"tfc:rock/raw/granite","tfc:rock/raw/diorite","tfc:rock/raw/gabbro","tfc:rock/raw/schist","tfc:rock/raw/gneiss","minecraft:blackstone",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("soapstone", 30),new OreVeinInfoRecipe.WeightedBlock("talc", 20),new OreVeinInfoRecipe.WeightedBlock("glauconite_sand", 25),new OreVeinInfoRecipe.WeightedBlock("pentlandite", 15),new OreVeinInfoRecipe.WeightedBlock("trona", 10),},
				null),
			new OreVeinInfoRecipe("nether_magnetite", "minecraft:the_nether", 
				205, 0.4, 0, 128, 39, 0, 0, new String[] {
				"minecraft:deepslate","minecraft:blackstone","tfc:rock/raw/basalt","minecraft:dripstone_block",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("magnetite", 20),new OreVeinInfoRecipe.WeightedBlock("vanadium_magnetite", 30),new OreVeinInfoRecipe.WeightedBlock("chromite", 10),new OreVeinInfoRecipe.WeightedBlock("gold", 30),new OreVeinInfoRecipe.WeightedBlock("sapphire", 10),},
				null),
			new OreVeinInfoRecipe("nether_manganese", "minecraft:the_nether", 
				225, 0.4, 32, 128, 45, 0, 0, new String[] {
				"minecraft:deepslate","tfc:rock/raw/basalt","minecraft:blackstone","minecraft:dripstone_block",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("grossular", 37),new OreVeinInfoRecipe.WeightedBlock("spessartine", 25),new OreVeinInfoRecipe.WeightedBlock("pyrolusite", 25),new OreVeinInfoRecipe.WeightedBlock("tantalite", 12),},
				null),
			new OreVeinInfoRecipe("nether_mica", "minecraft:the_nether", 
				220, 0.35, 32, 128, 41, 0, 0, new String[] {
				"tfc:rock/raw/granite","tfc:rock/raw/diorite","tfc:rock/raw/gabbro","tfc:rock/raw/schist","tfc:rock/raw/gneiss","minecraft:blackstone",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("kyanite", 46),new OreVeinInfoRecipe.WeightedBlock("mica", 33),new OreVeinInfoRecipe.WeightedBlock("pollucite", 20),},
				null),
			new OreVeinInfoRecipe("nether_molybdenum", "minecraft:the_nether", 
				245, 0.55, 0, 128, 31, 0, 0, new String[] {
				"tfc:rock/raw/gneiss","tfc:rock/raw/schist","tfc:rock/raw/granite","tfc:rock/raw/diorite","tfc:rock/raw/gabbro","minecraft:blackstone",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("wulfenite", 42),new OreVeinInfoRecipe.WeightedBlock("molybdenite", 31),new OreVeinInfoRecipe.WeightedBlock("powellite", 10),new OreVeinInfoRecipe.WeightedBlock("nickel", 15),},
				null),
			new OreVeinInfoRecipe("nether_monazite", "minecraft:the_nether", 
				245, 0.35, 24, 128, 45, 0, 0, new String[] {
				"tfc:rock/raw/granite","tfc:rock/raw/diorite","tfc:rock/raw/gabbro","tfc:rock/raw/schist","tfc:rock/raw/gneiss","minecraft:blackstone",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("bastnasite", 50),new OreVeinInfoRecipe.WeightedBlock("monazite", 25),new OreVeinInfoRecipe.WeightedBlock("neodymium", 25),},
				null),
			new OreVeinInfoRecipe("nether_naquadah", "minecraft:the_nether", 
				200, 0.7, 0, 38, 32, 0, 0, new String[] {
				"minecraft:blackstone","tfc:rock/raw/basalt",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("naquadah", 100),},
				null),
			new OreVeinInfoRecipe("nether_olivine", "minecraft:the_nether", 
				250, 0.35, 24, 128, 31, 0, 0, new String[] {
				"minecraft:deepslate","tfc:rock/raw/basalt","minecraft:blackstone","minecraft:dripstone_block",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("bentonite", 35),new OreVeinInfoRecipe.WeightedBlock("magnesite", 25),new OreVeinInfoRecipe.WeightedBlock("olivine", 25),new OreVeinInfoRecipe.WeightedBlock("glauconite_sand", 15),},
				null),
			new OreVeinInfoRecipe("nether_pitchblende", "minecraft:the_nether", 
				250, 0.55, 0, 128, 24, 0, 0, new String[] {
				"tfc:rock/raw/granite","tfc:rock/raw/diorite","tfc:rock/raw/gabbro","tfc:rock/raw/schist","tfc:rock/raw/gneiss","minecraft:blackstone",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("pitchblende", 62),new OreVeinInfoRecipe.WeightedBlock("uraninite", 25),new OreVeinInfoRecipe.WeightedBlock("wulfenite", 12),},
				null),
			new OreVeinInfoRecipe("nether_quartz", "minecraft:the_nether", 
				150, 0.4, 0, 128, 45, 0, 0, new String[] {
				"minecraft:deepslate","minecraft:blackstone","tfc:rock/raw/basalt","minecraft:dripstone_block","tfc:rock/raw/granite","tfc:rock/raw/diorite","tfc:rock/raw/gabbro",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("quartzite", 25),new OreVeinInfoRecipe.WeightedBlock("nether_quartz", 54),new OreVeinInfoRecipe.WeightedBlock("barite", 20),},
				null),
			new OreVeinInfoRecipe("nether_redstone", "minecraft:the_nether", 
				160, 0.5, 0, 128, 45, 0, 0, new String[] {
				"tfc:rock/raw/granite","minecraft:blackstone",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("redstone", 45),new OreVeinInfoRecipe.WeightedBlock("ruby", 35),new OreVeinInfoRecipe.WeightedBlock("cinnabar", 20),},
				null),
			new OreVeinInfoRecipe("nether_saltpeter", "minecraft:the_nether", 
				210, 0.4, 32, 128, 50, 0, 0, new String[] {
				"tfc:rock/raw/granite","tfc:rock/raw/diorite","tfc:rock/raw/gabbro","tfc:rock/raw/schist","tfc:rock/raw/gneiss","minecraft:blackstone",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("saltpeter", 35),new OreVeinInfoRecipe.WeightedBlock("diatomite", 25),new OreVeinInfoRecipe.WeightedBlock("electrotine", 25),new OreVeinInfoRecipe.WeightedBlock("alunite", 15),},
				null),
			new OreVeinInfoRecipe("nether_sapphire", "minecraft:the_nether", 
				180, 0.45, 0, 128, 33, 8, 0, new String[] {
				"tfc:rock/raw/gabbro","tfc:rock/raw/granite","tfc:rock/raw/gneiss","tfc:rock/raw/diorite","tfc:rock/raw/schist","minecraft:blackstone",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("almandine", 38),new OreVeinInfoRecipe.WeightedBlock("pyrope", 27),new OreVeinInfoRecipe.WeightedBlock("sapphire", 16),new OreVeinInfoRecipe.WeightedBlock("green_sapphire", 16),},
				null),
			new OreVeinInfoRecipe("nether_scheelite", "minecraft:the_nether", 
				180, 0.45, 0, 128, 25, 0, 0, new String[] {
				"tfc:rock/raw/granite","tfc:rock/raw/diorite","tfc:rock/raw/gabbro","tfc:rock/raw/gneiss","tfc:rock/raw/schist","minecraft:blackstone",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("scheelite", 45),new OreVeinInfoRecipe.WeightedBlock("tungstate", 35),new OreVeinInfoRecipe.WeightedBlock("lithium", 20),},
				null),
			new OreVeinInfoRecipe("nether_silver", "minecraft:the_nether", 
				160, 0.5, 24, 128, 45, 0, 0, new String[] {
				"tfc:rock/raw/granite","tfc:rock/raw/gneiss","minecraft:blackstone",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("galena", 30),new OreVeinInfoRecipe.WeightedBlock("silver", 35),new OreVeinInfoRecipe.WeightedBlock("lead", 35),},
				null),
			new OreVeinInfoRecipe("nether_sphalerite", "minecraft:the_nether", 
				170, 0.5, 32, 128, 45, 0, 0, new String[] {
				"minecraft:deepslate","tfc:rock/raw/basalt","minecraft:blackstone","minecraft:dripstone_block",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("sulfur", 35),new OreVeinInfoRecipe.WeightedBlock("sphalerite", 40),new OreVeinInfoRecipe.WeightedBlock("pyrite", 25),},
				null),
			new OreVeinInfoRecipe("nether_sulfur", "minecraft:the_nether", 
				165, 0.3, 0, 128, 50, 0, 0, new String[] {
				"tfc:rock/raw/diorite","tfc:rock/raw/basalt","minecraft:blackstone","tfc:rock/raw/schist",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("sulfur", 50),new OreVeinInfoRecipe.WeightedBlock("pyrite", 35),new OreVeinInfoRecipe.WeightedBlock("sphalerite", 15),},
				null),
			new OreVeinInfoRecipe("nether_tetrahedrite", "minecraft:the_nether", 
				170, 0.5, 32, 128, 45, 0, 0, new String[] {
				"minecraft:deepslate","minecraft:dripstone_block","tfc:rock/raw/schist","tfc:rock/raw/gneiss","minecraft:blackstone",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("tetrahedrite", 50),new OreVeinInfoRecipe.WeightedBlock("copper", 30),new OreVeinInfoRecipe.WeightedBlock("stibnite", 20),},
				null),
			new OreVeinInfoRecipe("nether_topaz", "minecraft:the_nether", 
				180, 0.4, 0, 128, 33, 7, 0, new String[] {
				"minecraft:blackstone","minecraft:deepslate","tfc:rock/raw/basalt","minecraft:dripstone_block",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("blue_topaz", 35),new OreVeinInfoRecipe.WeightedBlock("topaz", 25),new OreVeinInfoRecipe.WeightedBlock("chalcocite", 25),new OreVeinInfoRecipe.WeightedBlock("bornite", 15),},
				null),
			new OreVeinInfoRecipe("venus_manual_salt", "ad_astra:venus", 
				30, 0.2, 40, 65, 20, 6, 0, new String[] {
				"minecraft:dripstone_block","ad_astra:venus_stone","tfc:rock/raw/basalt","tfc:rock/raw/rhyolite","tfc:rock/raw/dacite","tfc:rock/raw/andesite","betterend:flavolite","betterend:sandy_jadestone",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("salt", 80),new OreVeinInfoRecipe.WeightedBlock("rock_salt", 10),new OreVeinInfoRecipe.WeightedBlock("lepidolite", 5),new OreVeinInfoRecipe.WeightedBlock("spodumene", 5),},
				new String[] {"ore_vein.tfg.venus_manual_salt.emi.0"}),
			new OreVeinInfoRecipe("venus_manual_sulfur", "ad_astra:venus", 
				30, 0.2, 40, 65, 20, 0, 0, new String[] {
				"minecraft:dripstone_block","ad_astra:venus_stone","tfc:rock/raw/basalt","tfc:rock/raw/rhyolite","tfc:rock/raw/dacite","tfc:rock/raw/andesite","betterend:flavolite","betterend:sandy_jadestone",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("sulfur", 80),new OreVeinInfoRecipe.WeightedBlock("pyrite", 15),new OreVeinInfoRecipe.WeightedBlock("sphalerite", 5),},
				new String[] {"ore_vein.tfg.venus_manual_sulfur.emi.0"}),
	};
}
